### ISSUE TITLE
Tracker: Templates & Guides

### ISSUE THREAD

**Issue by daniellex0** [hackforla/UI-UX#15]
### Overview
This is an issue to track the templates and guides we have available at UI/UX Community of Practice

### Action Items

| Guide           | Template Link                                                                                                          | Issue                                                            | Status      |
| --------------- | ---------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------- | ----------- |

### Resources/Instructions
[Spreadsheet Converter](https://tabletomarkdown.com/convert-spreadsheet-to-markdown/)
[Templates and Guides Google Sheet]()

**Comment by anonymousanemone** [comment]
Working on issue #48

**Comment by ExperimentsInHonesty** [comment]
The guides team needs to make changes to guide labeling and a few other things related to guide issues.  The details of that will be listed here. When we make changes we will put this issue in the review column so that Leadership of the community of practice will be aware of the recent changes.

**Comment by amzzzs** [comment]
**Create a guide: card sorting** #58

**Comment by amzzzs** [comment]
Working on issue #58 Create a guide to card sorting

**Comment by aileengiang** [comment]
Working on issue #62 "Figma Auto-Layout"

**Comment by pogwon** [comment]
Working on issue #29 "Guide: Effective practices for user testing"

**Comment by fchan218** [comment]
<details><summary>Assignee, Labels, Project Board Placement, and Milestones for this issue in the UI/UX Repo:</summary>
<p>
<img width="332" alt="Screenshot 2024-10-23 at 8 02 25 PM" src="https://github.com/user-attachments/assets/d2978103-2a30-48a9-a0ac-735de5484571">
</p>
</details>
