### ISSUE TITLE
Guide: Design System resources

### ISSUE THREAD

**Issue by daniellex0** [hackforla/UI-UX#18]
### Overview
We need to create a guide with design system resources so that designers at Hack for LA have helpful/insightful information and resources to work on their design systems.

### Action Items
- [ ] Research existing up-to-date resources about design systems - articles, tools, etc.
   - [ ] Once done, remove the "Guide: Research" label and add the "Guide: Gather Examples" label
- [ ] Gather examples of how other projects or volunteers have created their design systems, including resources and tools they used, adding each example as a link in the resources section below
   - [ ] Once done, remove the "Guide: Gather Examples" label and add the "Guide: Draft Guide" label
- [ ] Create a draft resource guide, either in markdown format in this issue or a google doc in the [ux/ui google drive]
    - [ ] Once done, remove the "Guide: Draft Guide" label and add the "Guide: Review Guide" label
- [ ] Review the guide with UX/UI community of practice
   - [ ] Once done, remove the "Guide: Review Guide" label and add the "Guide: Leadership Review" label
- [ ] Present to the Hack for LA leadership team for sign off
   - [ ] Once approved, remove the "Guide: Leadership Review" label and add the "Guide: Place Guide" label

### Resources
Update issue #15 with the name of item you are working on

**Comment by fchan218** [comment]
<details><summary>Assignee, Labels, Project Board Placement, and Milestones for this issue in the UI/UX Repo:</summary>
<p>
<img width="363" alt="Screenshot 2024-10-23 at 8 00 13 PM" src="https://github.com/user-attachments/assets/21137ab9-637b-4cd4-9e88-5a5ee4153da1">
</p>
</details>
