### ISSUE TITLE
Who are the HackforLA Stakeholders?

### ISSUE THREAD

**Issue by Oskar-Adam-Zloch** [hackforla/UI-UX#2]
### Overview
I would like to know who are the stakeholders, 
in order to get their input about the organization identity

### Stakeholders

- Full Name - role in the organization

**Comment by ExperimentsInHonesty** [comment]
Bonnie Wolfe, Executive Director and Director of Product
Olivia Chiong, Director of Operations

**Comment by ExperimentsInHonesty** [comment]
The Community of Practice leads can be found here: https://www.hackforla.org/communities-of-practice
