### ISSUE TITLE
Guide: Effective Practices for working with developers

### ISSUE THREAD

**Issue by daniellex0** [hackforla/UI-UX#26]
### Overview
We need to create a guide about effective practices for designers working with developers for designers to reference and learn from, and to promote smooth communication and collaboration between design and development on Hack for LA teams.

### Action Items
- [x] Research existing information about effective communication between designers and developers in relevant resources, online articles, etc.
   - [x] Once done, remove the "Guide: Research" label and add the "Guide: Gather Examples" label
- [x] Gather examples of effective practices from other projects during a community of practice brainstorming session
   - [x] Once done, remove the "Guide: Gather Examples" label and add the "Guide: Draft Guide" label
- [x] Create a draft guide, either in markdown format in this issue or a google doc in the [ux/ui google drive]
    - [x] Once done, remove the "Guide: Draft Guide" label and add the "Guide: Review Guide" label
- [x] Review the guide with UX/UI community of practice
   - [x] Once done, remove the "Guide: Review Guide" label and add the "Guide: Leadership Review" label
- [x] Present to the Hack for LA leadership team for sign off
   - [x] Once approved, remove the "Guide: Leadership Review" label and add the "Guide: Place Guide" label

### Resources
Update issue #15 with the name of item you are working on

[Guide](https://docs.google.com/document/d/1YlACBPOXVzFyrk1vCwXyC9ylp5KwATJ2NlR5VlMpk6Y/edit)

**Comment by daniellex0** [comment]
Examples of what can be included:

- working with limitations
- communication avenues
- platforms in common
- breaking down barriers

**Comment by daniellex0** [comment]
Guide: https://docs.google.com/document/d/1YlACBPOXVzFyrk1vCwXyC9ylp5KwATJ2NlR5VlMpk6Y/edit

(located in [this](https://drive.google.com/drive/folders/12-5ZkSa4nVtZMPWe0Rp8bPVPvMubbBda) folder)

**Comment by ExperimentsInHonesty** [comment]
This guide is well written. The only remaining items seems to be making it conform to the guide template (which has changed a little since this guide was originally developed.

**Comment by fchan218** [comment]
<details><summary>Assignee, Labels, Project Board Placement, and Milestones for this issue in the UI/UX Repo:</summary>
<p>
<img width="332" alt="Screenshot 2024-10-23 at 6 27 15 PM" src="https://github.com/user-attachments/assets/ba750b0c-d95e-4500-853e-9796480ca98f">
</p>
</details>

**Comment by fchan218** [comment]
@daniellex0 This guide issue is moving to the knowledgebase-content repo. If you would like to maintain edit access to the issue and its associated files, please fill out the [Google Drive Access Form](https://forms.gle/vnKRqprNYJUG5ET69).
