### ISSUE TITLE
Gather Examples: Figma Auto-Layout

### ISSUE THREAD

**Issue by Eloks7** [hackforla/UI-UX#281]
### Overview
Hack for LA communities of practice (Product-Management and UI/UX) need to know if your team have ever made use of Auto-Layout in your designs. We are creating a guide for Figma Auto-Layout so that volunteers at HfLA can start utilizing industry-standard auto-layout capabilities in their designs

### Action Items
If your project does/doesn't use Auto-Layout, please leave a comment using the below template.

- Name of Project
- Has Auto-Layout ever been utilized by your team?
- Links to resources/Figma files where Auto-Layout was used ( no need to grant edit access).
- Names of components that Auto-Layout was used on.

**Comment by ExperimentsInHonesty** [comment]
- Not sure this issue is actually needed.  Its a subset of this issue https://github.com/hackforla/UI-UX/issues/62.  I think the person assigned to 62 will just need to follow up appropriately.
