### ISSUE TITLE
We would need few experienced front-end developers onboard

### ISSUE THREAD

**Issue by Oskar-Adam-Zloch** [hackforla/UI-UX#3]
### Overview

It's very crucial to involve developers in the designing early on, in order to optimize designs handoff, and have someone constraining the designs, so those would match the technology used in the project development.

Ask experienced developers, if they would like to be taking part in designing processes, and become stakeholder.
### To become developer stakeholder for the design, they would need to:
- [ ] Be experienced with the technology used in this project
- [ ] Understand the project structure and how it is supposed to work
- [ ] Have enough time and motivation to work with both developer and desiger teams

**Comment by ExperimentsInHonesty** [comment]
@Oskar-Adam-Zloch its not clear what the action items here are.  If this is general guidance for projects, please indicate that what is needed is a guide for X and this is Y part of that guide.  Otherwise if its not, please elaborate
