### ISSUE TITLE
Contacting Past Guest Speakers for UI/UX CoP [Logo Design & YouTube]

### ISSUE THREAD

**Issue by bradyse** [hackforla/UI-UX#311]
### Overview
HfLA has a YouTube Channel, and the UI/UX CoP needs to create a YouTube Channel for all Guest Speakers.

### Action Items

- [x] Complete Consent Form Guide to create a template [Version 1 complete, CoP Co-leads working on Version 2] 
- [x] Create separate issues for Consent form, LOGO design and YouTube Channel to effectively monitor the progress of each

### Resources/Instructions
[UI/UX Wiki of Past Speakers](https://github.com/hackforla/UI-UX/wiki/Past-Speakers)
[Guide Consent Form Issue](https://github.com/hackforla/UI-UX/projects/1#card-63116901)
[Draft of Consent Template](https://docs.google.com/document/d/1bUx5U9GscgFQaSc4W1wnd7H2IKbBw4h2/edit)

**Comment by Aparna1Gopal** [comment]
@bradyse @Aparna1Gopal @MariaElizabeth04 @pbahle @ExperimentsInHonesty 

Related to the UI/UX Community of Practice 
Logo and Youtube Update

**Comment by Nat-nn** [comment]
Link to the list of Past UI/ UX Community of Practice Speakers
https://docs.google.com/spreadsheets/d/1nSPHlUwINB7YJ6nFr_jrWTIA_yg74qlmUkcTjYyfzQA/edit?usp=sharing

**Comment by bradyse** [comment]
@Aparna1Gopal @Nat-nn has added a draft of the consent document (under resources). Perhaps, we should ask Bonnie for approval on this document?

**Comment by Aparna1Gopal** [comment]
@bradyse Yes! Once Bonnie approves the final consent document, @Nat-nn can start sending it to our Speakers. Also, @bradyse @Nat-nn I made two comments on this draft consent document. Could you please review it and give your feedback. Thanks!

**Comment by Aparna1Gopal** [comment]
Also, @bradyse @Nat-nn I made two comments on this draft consent document. Could you please review it and give your feedback. Thanks!

**Comment by Aparna1Gopal** [comment]
**Notes from Slack Communication:** 

Hi at Sara Brady, following up on our conversation regarding the Consent forms. I realized when we spoke, I forgot about the consent for photographs.
In Australia we need to draft the following: general consent to conduct the research itself (as in talking to research participants, interviewing, collecting their data, oral history, any written resources etc.), consent for photographs, consent for videos, consent for audio. Next, we also need to specify processes for secure data storage & transmission (data dissemination). Based on the vulnerability/at risk category of the research participants: the level of security for data storage & how the data is transmitted to the general audience will vary (example: anonymized data etc).
In Australia we have individual consent forms for each. In our case at Hack for LA’s UI/UX CoP , we could probably have just one form with check boxes for interviewing, resources, audio, video, photographs etc. Please let me know if you would like me to collect any further information. Many thanks!

**Comment by Aparna1Gopal** [comment]
**Notes:**

**Consent: current email template to seek consent from guest speakers** 

Hi [NAME],
Thank you for being willing to speak to our group! In lieu of having a proper consent form document, we'd appreciate if you could respond all to this email regarding your consent for the following:
- Recording the presentation
- Storing it on our shared internship drive
- Sharing the link with UI/UX members.
- Hosting and sharing your talk on the UI/UX Community of Practice's You Tube Channel

**Comment by Aparna1Gopal** [comment]
Notes

Create separate Issues for Logo Design, Consent Forms and YouTube channel. To effectively monitor the progress of each. 
Further information found under: https://github.com/hackforla/UI-UX/issues/187#issuecomment-1374170451

**Comment by Aparna1Gopal** [comment]
- The UI/UX CoP leads are working on Version 2 of the consent form for guest speakers. 
- This issue pertaining to consent form (Version 1) is hence being closed and is being tracked in a new issue.
