### ISSUE TITLE
Create a Guide/Template: Favicons

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/UI-UX#32]
### Overview
We need to create a guide for creating favicons so that teams can create unique favicons for their projects.

### Action Items
- [ ] Gather examples of how other projects or volunteers have done this (if applicable), adding each example as a link in the resources section below
   - [ ] Once done, remove the "Guide: Gather Examples" label and add the "Guide: Research" label
- [ ] Research existing information about [name of item] in [relevant resources, articles, etc.]
   - [ ] Once done, remove the "Guide: Research" label and add the  "Guide: Draft Guide" label
- [ ] Create a draft guide, either in markdown format in this issue or a google doc in the [ux/ui google drive]
    - [ ] Once done, remove the "Guide: Draft Guide" label and add the "Guide: Review Guide" label
- [ ] Review the guide with UX/UI community of practice
   - [ ] Once done, remove the "Guide: Review Guide" label and add the "Guide: Leadership Review" label
- [ ] Present to the Hack for LA leadership team for sign off
   - [ ] Once approved, remove the "Guide: Leadership Review" label and add the "Guide: Place Guide" label

### Resources
Update issue #15 with the name of item you are working on
[Resource from 100 Automations](https://github.com/100Automations/Website/issues/100)

**Comment by Aparna1Gopal** [comment]
As per [Instructions](https://github.com/hackforla/UI-UX/projects/1#card-91969059) moving this to [Backlog column](https://github.com/hackforla/UI-UX/projects/1#column-12351486)

**Comment by fchan218** [comment]
<details><summary>Assignee, Labels, Project Board Placement, and Milestones for this issue in the UI/UX Repo:</summary>
<p>

<img width="336" alt="Screenshot 2024-10-23 at 6 24 40 PM" src="https://github.com/user-attachments/assets/d6fb84c0-eb2c-4807-85a6-7dc82e1a858b">
</p>
</details>
