### ISSUE TITLE
Create UX Interview Questions Repository

### ISSUE THREAD

**Issue by Nat-nn** [hackforla/UI-UX#351]
### Overview
We are going to use this issue to collect the list of UX / UI interview questions for HfLA volunteers who are on the job market.

### Action Items
- [x] Create a list of interview questions by adding comments to this issue
- [x] Create a document of this questions, organized by type
- [x] Add Link to document in the resources of this issue 
- [x] Review questions by several UX leads and HfLA alum
- [x] Add document to CoP wiki page

### Resources/Instructions
- [Interview Question List](https://docs.google.com/spreadsheets/d/1bf_a2BspSsLQTUw1EGCwBz5pTrmkRGaI7F8XGFozB1o/edit?usp=sharing)
- [Simon W. Taylor's Slide deck - see slides 6 & 7](https://docs.google.com/presentation/d/1uVnPf9eFXpZxoxslXxtn9TeJDQbGgIonjepfoj7FkOI/edit?usp=sharing)
- [UI/UX CoP: Interview Questions](https://docs.google.com/document/d/1ELYmWQ8L-ysJTOPPzmqGOr62Oz9FGRAP9bm9Q8RAzYQ/edit?usp=sharing)
- [UI/UX Interview Workshop Resources Folder](https://drive.google.com/drive/folders/1d6e8NN19VS3u3Z8KO_695D9BvpdWbbjs)

**Comment by breatalsness** [comment]
@Nat-nn - Dropping in a few from my interviews, some may be relevant to both UX/UI roles. Separately, this is also a helpful [resource](https://www.userinterviews.com/blog/common-ux-research-job-interview-questions-how-to-answer-them). They've done a good job categorizing the questions, perhaps a little inspiration for organizing this. 

1. We have a subscription growth issue. How would you go about researching it?
2.  Have you ever received a negative feedback, how have you handled that?
3. Describe a recent research study you did that resulted in a large amount of data. How did you analyze the data, and how did you come up with insights and recommendations to improve the team?
4. We have a subscription growth issue. How would you go about researching it?
5. How do you deal with circumstances in which individuals are doubtful of the value of your research, for example, when they challenge your sample size?
6. Walk me through this: How do you design a research study for a new or concept product that focus group participants may not fully understand?
7. Describe the type of research methods you prefer to use. What would you consider to be your main methods of expertise?

**Comment by bradyse** [comment]
@Nat-nn: Great work on the questions. It looks like the link that you shared with me in Slack is not located inside the shared UI/UX Google Drive. I saved that link in the resources of this issue. Could you please move this file into the UI/UX Google Drive folder?

Then you can update this issue according to the template below.

Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Aparna1Gopal** [comment]
@Nat-nn Came across these DEI related behavior-based interview questions:

- Tell me about what you’ve done to create an inclusive culture in the past.
- Tell me about a time you went out of your way or had to be creative about including others.
- Tell me about a time when you witnessed exclusionary behaviour and how you handled that situation.
- How do you model inclusion in your leadership or management style?
- How do you demonstrate a commitment to diversity, equity, and inclusion at work?

By: Written by Vinciane de Pape, DEI Advisory Lead at Bloom, on Bloom Blog

**Comment by Aparna1Gopal** [comment]
Added by Aparna G, questions contributed by Sara B

**Behavioral Questions**

Asked by multiple companies:
-	Tell me about yourself.
-	Why do you want to work for us? 
-	Note: Prepare answers that speak both about the company and the team (if you already know which team you’re applying for)
-	What UX research methods have you used in the past?
-	What are your salary expectations?
-	What is a project you are proud of? 
-	Tell me about a time when you were creative. 
-	Tell me about a time when you worked with a difficult person and how you handled it
-	Tell me about a time you messed up or failed
-	What are you looking for in your next role? 
-	What would you do if your stakeholder came to you and asked to do research? What’s your process?
-	What is the nicest work compliment that you’ve ever received?
-	When have you received criticism or negative feedback? How did you handle it?
-	Do you have any questions for me? 
Asked at least once:
-	Why are you leaving the current company/role?
-	Note: This may be important if it’s the first job out of academia
-	Tell me about what type of research you have done in the past. 
-	Note: Discuss all UXR methods used and at which stage
-	Walk me through UX research you have done in the past 
-	Note: This is a mini version of a portfolio presentation
-	What is a project you are not confident with?
-	What are your strengths or weaknesses? 
-	Tell me about a time when you saved the day/solved a big problem, overcame an obstacle
-	Tell me about a time you are proud of, you achieved something great
-	Tell me about a time you exhibited leadership
-	Tell me about a time where you had to work as a team
-	How would you convince stakeholders who have completely different backgrounds from your users so they don’t understand cultural subtleties?
-	Imagine that two different people from different teams approached you and wanted a deliverable from you but you only had time to work on one thing. How would you approach this situation?

Technical Questions 
(asked at Tech companies) 
Can be accessed here:

**Comment by Aparna1Gopal** [comment]
Create new issue under UI/UX CoP Projects to track this issue https://github.com/hackforla/UI-UX/issues/351. This issue is depreciated and is currently being closed. The new corresponding issue will be created under UI/UX CoP Projects. It will be managed by the CoP Co-Leads. The new interview questions will be collected in the GitHub Issue & transferred to Google Docs by the UI/UX CoP Co-Leads. This is an ongoing issue and will be used during the monthly 'Interview Workshop Series' of the UI/UX Community of Practice.
