### ISSUE TITLE
Generate Questions for 2022-09-28: Maze Guest Speakers

### ISSUE THREAD

**Issue by bradyse** [hackforla/UI-UX#354]
### Overview
We need to create a list of questions for our guest speakers from Maze attending on Sept 28, 2022.

### Action Items
- [x] Send issue to UI/UX Slack channel and ask UI/UX people to write their questions in the comments.
- [x] Collate the questions into a list of unique questions (non-duplicated questions).
- [x] Send them to the guest speakers within 2 weeks of their talk.

### Resources/Instructions
- [UI/UX Slack Channel](https://hackforla.slack.com/archives/C017ESHSMNG)
- [Maze.co](https://maze.co/)

**Comment by breatalsness** [comment]
1. What are the important skills for a UX designer?
2. What's your approach to inclusive UX design? 
3. How do you prioritize feedback from your cross functional partners (User researchers, Product Management, Engineering)?

**Comment by Aparna1Gopal** [comment]
1. What does the day to day in the life of a UX Designer look like at Maze? 
2. What is Maze's biggest strength/advantage in the current market? What does the product provide that is special and not currently provided by others in the market?
3. What is Maze's biggest weakness in the current market? What is Maze's current product team currently working towards bridging which gap areas? 
4. What does the interview process at Maze look like? What are the top 3-5 criteria that Maze is looking for which hiring new employees? 
5. What does the structure and hierarchy look like at Maze? Where does UX Design and UX Research sit within the ecosystem?

**Comment by bradyse** [comment]
1. What recommendations do you have for people who are just starting their careers in UX? How could Maze be an important tool in their toolkit?
2. Who uses Maze more often? UX Designers or UX Researchers?
3. How challenging is it for you to design products where the users are other designers and researchers? Do you still ascribe to the NN/g mantra that you're not the user?

**Comment by bkobak33** [comment]
1. Are there particular clients/industries (not asking for specifics!) where you have faced challenges advocating for UX research? How have you handled the skepticism?
2. What are some Maze's most popular products/templates? Why?

**Comment by bradyse** [comment]
### Questions for Maze UX Designers

1. **Can you share information about Maze as a company?**
     - What are some of Maze's most popular products/templates? Why?
     - Who uses Maze's products the most often? Is it only UX designers and UX researchers?
     - What is Maze's biggest strength/advantage in the current market? 
          - What does the product provide that is special and not currently provided by others in the market?
     - What is Maze's biggest weakness in the current market? 
          - What gap area is Maze's current product team working towards bridging?

2. **What is it like being a UX designer at Maze?**
     - What does the structure and hierarchy look like at Maze? Where does UX Design and UX Research sit within the ecosystem?  
     - What does the day-to-day in the life of a UX Designer look like at Maze?
     - How do you prioritize feedback from your cross functional partners (User researchers, Product Management, Engineering)?
     - What's your approach to inclusive UX design?

3. **Can you share what it's like working as UX Designers?**
     - Are there particular clients/industries (not asking for specifics!) where you have faced challenges advocating for UX research
     - Have you experienced skepticism on the need for UX researchers to support UX design? If so, how did you handle it?
     - How challenging is it for you to design products where the users are other designers and researchers? 
          - Do you still ascribe to the Nielsen Norman Group mantra that you're not the user?

4. **Do you have any advice for people trying to get into User Experience?**
     - What recommendations do you have for people who are just starting their careers in UX? 
          - How could Maze be an important tool in their toolkit?
     - What does the interview process at Maze look like? 
          - What are the top 3-5 criteria that Maze is looking for while hiring new employees?
     - What are the important skills for a UX designer?
