### ISSUE TITLE
Generate Questions for 2022-09-10: Maria Elizabeth Rodriguez Beltran

### ISSUE THREAD

**Issue by bradyse** [hackforla/UI-UX#356]
### Overview
We need to create a list of questions for our guest speaker, Maria Elizabeth, attending on 2022-09-10.

### Action Items
- [x] Send issue to UI/UX Slack channel and ask UI/UX people to write their questions in the comments.
- [x] Collate the questions into a list of unique questions (non-duplicated questions).
- [x] Send them to the guest speakers within 2 weeks of their talk.

### Resources/Instructions
- [UI/UX Slack Channel](https://hackforla.slack.com/archives/C017ESHSMNG)
- [Maria's LinkedIn Profile](https://www.linkedin.com/in/mariaelizabeth-rodriguezbeltran/)

**Comment by bradyse** [comment]
**Announcement: UI-UX CoP Meeting!**
:star-struck: Guest Speaker: HfLA Alum [Maria Elizabeth Rodriguez Beltran](https://www.linkedin.com/in/mariaelizabeth-rodriguezbeltran/)
:sparkles: About Maria: She is a newly minted UXR for The Philadelphia Inquirer (since July) and was previously a researcher for the Rutgers Institute for the Study of Global Racial Justice, as well as a CoP lead for your very own UI-UX Community of Practice!
:technologist: Topic: Her story on transitioning from academia into UX research
:clock6: When: Wednesday 6 pm PST
:question: Post your questions for Maria to this [issue](https://github.com/hackforla/UI-UX/issues/356).

**Comment by bradyse** [comment]
1. How long did it take you to fully transition from a pure academic role to a UXR role?
2. What were some ways that you communicated impact for your academic research to your current employers?
3. How did you handle rejection and setbacks in your UXR journey? Were there times that you wanted to give up? If so, what made you not give up?

**Comment by Aparna1Gopal** [comment]
1. Your interview process for this role: How did you prepare? What resources did you use? 

2. Your take on portfolios: Did you have to present your portfolio during the interview and what were your steps? What type of projects did you present and what were the aspects you highlighted on?

**Comment by alice-milmac** [comment]
1. Did you go through a technical interview for this role and if so, how did you prepare for that?
2. Can you share a little bit about the process of working with other stakeholders (e.g. designer, product managers) in the initial stages of a project and how you develop a research question and select the best research method for that project?

**Comment by bkobak33** [comment]
1. How did your time at HfLA change or influence your transition from academia to UX? At what point did you start sharing the work here on your resume or interview answers?

**Comment by bradyse** [comment]
#### Questions for Maria Elizabeth

1. **Can you provide some background context of your journey into your UXR role?**
     - How long did it take you to fully transition from a pure academic role to a UXR role?
     - How did you handle rejection and setbacks in your UXR journey? 
     - Were there times that you wanted to give up? If so, what made you not give up?
     - How did your time at HfLA change or influence your transition from academia to UX?
2. **Can you explain the interview process that you experienced for this role?**
     - What resources did you use? 
     - At what point did you start sharing your HfLA work on your interview answers?
     - Did you go through a technical interview for this role?
          - If so, how did you prepare for that?
          - If not, were there other ways you prepared for the interview?
3. **What is your take on portfolios and explaining your previous research?**
     - Did you have to present your portfolio during the interview and what were your steps? 
     - If so, what type of projects did you present and what were the aspects you highlighted on?
     - What were some ways that you communicated impact for your academic research to your current employers?
     - Did you put HfLA on your resume? If so, when did you do this and did you change how it looked on your resume over time?
4. **What is your current role like?**
     - Can you share a little bit about the process of working with other stakeholders (e.g. designer, product managers) in the initial stages of a project?
     - How do you develop a research question and select the best research method for that project?
