### ISSUE TITLE
Generate Questions for 2022-11-16: Helen Lin, UX Researcher

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/UI-UX#373]
### Overview
We need to create a list of questions for our guest speaker Helen Lin, UX Researcher attending on 2022-11-16.

### Action Items
- [x] Send issue to UI/UX Slack channel and ask UI/UX people to write their questions in the comments.
- [x] Collate the questions into a list of unique questions (non-duplicated questions).
- [x] Send them to the guest speakers within 1 week of their talk.

### Resources/Instructions
- [UI/UX Slack Channel](https://hackforla.slack.com/archives/C017ESHSMNG)
- [Helen Lin, LinkedIn](https://www.linkedin.com/in/helenleelin/)

**Comment by Aparna1Gopal** [comment]
**Slack Announcement:** 

:wave: :mega: Mark your Calendars!
Helen Lin, UX Researcher will be visiting the UI/UX Community of Practice on November 16th!
Topic: Reflections and experiences as a UX Researcher

:computer: Please post your questions for Helen in this GitHub issue

Thank you!
UI/UX CoP co-leads

**Comment by Aparna1Gopal** [comment]
Reflections and experiences as a UX Researcher one year, hence: 

- What does your day-to-day on the job look like? 
- What was the process of moving between contracts (since your LinkedIn mentions moving from Tik Tok to Meta)? 
- What are your success strategies? 
- What are your must-have interviewing tips? 
- What are your tips on salary negotiation?

**Comment by wein4102** [comment]
How do you handle imposter syndrome? 
How do you address pushback from stakeholders?

**Comment by mxayavo1** [comment]
How do you handle when someone on your team suggests one research method but you suggest another way? I know there can be multiple ways to answer research questions but how do you break this problem down so both sides are validated but build consensus around one way?

**Comment by Aparna1Gopal** [comment]
**Slack Announcement: (reposted on November 07, 2022)** 

Aparna Gopal [1:02 PM](https://hackforla.slack.com/archives/C017ESHSMNG/p1667806328069509)
:mega: Mark your Calendars! Helen Lin, UX Researcher will be visiting the UI/UX Community of Practice on November 16th!
:computer: Topic: Reflections and experiences as a UX Researcher
:question:Please post your questions for Helen in this [GitHub issue](https://github.com/hackforla/UI-UX/issues/373):arrow_left: :arrow_down:
:bust_in_silhouette:About: Helen is a social psychology Ph.D. with a background in academic and healthcare research. After working with Hack for LA's "Brigade Organizers' Playbook" project in 2020, she landed contract roles at well-known social media companies. Her favorite part of UX research is sitting down with a user and really diving deep to learn who they are. 
:wave: [Helen's LinkedIn](https://www.linkedin.com/in/helenleelin/)
Thank you!
UI/UX CoP co-leads
[@Sara Brady](https://hackforla.slack.com/team/U0371AXAVUN)
 
[@Julia Gab](https://hackforla.slack.com/team/U03AS9FBAAU)
 
[@Aparna Gopal](https://hackforla.slack.com/team/U0245UJP868)

**Comment by Aparna1Gopal** [comment]
### Questions for Helen Lin, UX Researcher 

**1. Interviewing and the UX Job search**



**2. Day-to day in the life of a UX Researcher**


**3. Domain experience working in/with social media tech companies**

**Comment by Aparna1Gopal** [comment]
Reflections and experiences as a UX Researcher one year, hence:

What does your day-to-day on the job look like?
What was the process of moving between contracts (since your LinkedIn mentions moving from Tik Tok to Meta)?
What are your success strategies?
What are your must-have interviewing tips?
What are your tips on salary negotiation?
Working for social media companies and also as a UX Researcher we would like for you to share your knowledge & learn more on this topic: how do we work effectively regarding privacy and ethics surrounding teens/young adults and their social media use? What tips would you have for the UX'ers in our HfLA community on working with minors ethically and ensuring their safety & security?

How do you handle imposter syndrome?
How do you address pushback from stakeholders?

How do you handle when someone on your team suggests one research method but you suggest another way? I know there can be multiple ways to answer research questions but how do you break this problem down so both sides are validated but build consensus around one way?

**Comment by Aparna1Gopal** [comment]
**Slack Announcement: One day before the Speaker's visit**
**Promoting** the event/speaker, for increased attendance by sending reminder one day before the event** 


:mega: Helen Lin, UX Researcher will be visiting the UI/UX Community of Practice on November 16th at 6PM (Pacific Time)!
:computer: Topic: Reflections and experiences as a UX Researcher
:bust_in_silhouette:About: Helen is a social psychology Ph.D. with a background in academic and healthcare research. After working with Hack for LA's "Brigade Organizers' Playbook" project in 2020, she landed contract roles at well-known social media companies. Her favorite part of UX research is sitting down with a user and really diving deep to learn who they are.
:wave: [Helen's LinkedIn](https://www.linkedin.com/in/helenleelin/)
Thank you!
UI/UX CoP co-leads
at Sara Brady
at Julia Gab
at Aparna Gopal

**Comment by Aparna1Gopal** [comment]
**Transferring Notes: From WIKI - Potential Speakers**

INVITED & COMPLETED TALK ON November 16,2022 (Details here: https://github.com/hackforla/UI-UX/wiki/past-speakers)
- Helen Lin (Hack for LA Alumni)
- Employer: Meta, ex Tik Tok
- Date: 2022-08-12 (first contact made via Slack (cop leads channel) by Speaker) 
- Date: 2022-09-29 (second contact made via LinkedIn by COP Co-lead) 
- Topic: "It's been a year since the last Q&A and I've gained a LOT of experience since then! I would probably answer some of the questions differently now. I'd be open to either responding/reacting to my old video or doing a fresh Q&A" (Part 2 of speaker's first speaking session with the UI/UX CoP in 2021)
