### ISSUE TITLE
Generate Questions for 2023-01-18: Dr. Hyun Joo Sandy Oh/UC Irvine

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/UI-UX#400]
### Overview
We need to create a list of questions for our guest speaker Dr. Hyun Joo Sandy Oh/UC Irvine attending on 2023-01-18 (tentative)

### Action Items
- [x] Send issue to UI/UX Slack channel and ask UI/UX people to write their questions in the comments.
- [x] Collate the questions into a list of unique questions (non-duplicated questions).
- [x] Send them to the guest speakers within 2 weeks of their talk.

### Resources/Instructions
<details>
<summary>Slack Announcement (edit this)</summary>

:mega: Mark your Calendars! **Dr. Hyun Joo Sandy Oh/UC Irvine** will be visiting the UI/UX Community of Practice tentatively on **2023-01-18** at 6PM, PST!

:computer: **Topic:** **Knowing your audience: DEI research and empathy in the entertainment industry**
  
? Please post **your questions** in this [GitHub issue](https://github.com/hackforla/UI-UX/issues/400) :arrow_left: :arrow_down: 
  
:bust_in_silhouette:**About:** Dr. Hyun Joo Sandy Oh is an award-winning qualitative researcher, development consultant and DEI advocate with 15+ years of experience leading teams and research studies to inform decision making in media, entertainment and academia 

:wave: **[LinkedIn](https://www.linkedin.com/in/sandyoh/)**

We will be collecting questions until the end of the day Sunday, January 15th!

Thank you!
UI/UX CoP co-leads
@ Sara Brady @ Julia Gab @ Aparna Gopal

</details>

- [UI/UX Slack Channel](https://hackforla.slack.com/archives/C017ESHSMNG)
- https://www.linkedin.com/in/sandyoh/

### Speaker Bio
Dr. Hyun Joo Sandy Oh is an award-winning qualitative researcher, development consultant and DEI advocate with 15+ years of experience leading teams and research studies to inform decision making in media, entertainment and academia. Throughout her career, she has held positions around the world to conduct user and market research. Her research has been published in peer-reviewed journals and she's delivered talks and presentations on a global scale. Currently, she is leading UX research for Hack for LA's Youth Justice Navigator Project and serves as a Research Associate and Lecturer at UC Irvine. Dr. Oh is also leveraging her passion for DEI and research skills to advise and collaborate with executive producers, writers and studios on a number of scripted TV projects, including most recently Godfather of Harlem.

### Title
**Knowing your audience: DEI research and empathy in the entertainment industry**
(Title content recommended by Dr.Sandy)

**Comment by Aparna1Gopal** [comment]
- What academic research skills did you use while working on your TV Show & media? 
- What was the end-to-end research process while researching/prepping for 'Godfather of Harlem.' Where did you start, how did it proceed, when/where did you stop the research?
- How can academic researchers/other researchers find roles in media? Where/how should you apply?
- How is UX Research & researching for media interconnected? What are the transferable skills?

**Comment by Aparna1Gopal** [comment]
### Collated questions for Dr.Sandy

**As a career option**
Is researching for media a viable career opportunity? What are the advantages & disadvantages? Your advice to someone just starting out in this space.
How can academic researchers/other researchers find roles in media? Where/how should you apply?


**Training for the job** 
What academic research skills did you use while working on your TV Show & media?
What was the end-to-end research process while researching/prepping for 'Godfather of Harlem.' Where did you start, how did it proceed, when/where did you stop the research?

**Similarities/Differences: Research in entertainment & UX Research**
How is UX Research & researching for media interconnected? What are the transferable skills?

**Comment by Aparna1Gopal** [comment]
Slack Message (Announcement & Webinar Details) 

📣 Mark your Calendars! Dr. Hyun Joo Sandy Oh/UC Irvine will be visiting the UI/UX Community of Practice on 2023-01-25 at 6PM, PST!

💻 Topic: Knowing your audience: DEI research and empathy in the entertainment industry

👤About: Dr. Hyun Joo Sandy Oh is an award-winning qualitative researcher, development consultant and DEI advocate with 15+ years of experience leading teams and research studies to inform decision making in media, entertainment and academia

👋 https://www.linkedin.com/in/sandyoh/

Thank you!
UI/UX CoP co-leads
At Julia Gab At Sara Brady At Aparna Gopal

Here is a copy of the invite: ☝️⬆️

Hi there,

You are invited to a Zoom webinar.
When: Jan 25, 2023 06:00 PM Pacific Time (US and Canada)
Topic: A Conversation with Dr. Hyun Joo Sandy Oh

Register in advance for this webinar:
https://codeforamerica.zoom.us/webinar/register/WN_t7jNC2xQSeSEPXGf7NXr5g

After registering, you will receive a confirmation email containing information about joining the webinar.

**Comment by ExperimentsInHonesty** [comment]
Questions asked during the Q&A

- How does UX research inform film and television?
- How did you first come across that opportunity to work on the Godfather of Harlem? Did you already know you were looking for a type of opportunity like that?
- In your role, did you need to learn about writing (screenplay structure, etc.) and did that inform the information you provided?
- How did you learn to freelance?

**Comment by ExperimentsInHonesty** [comment]
Podcasts and videos from Samuel Proulx, Accessibility Evangelist at Fable
https://podcasts.apple.com/us/podcast/the-why-and-how-of-accessible-design/id1603036634?i=1000562170036
https://www.youtube.com/watch?v=SKMo60-PGJI&ab_channel=TheSpaceInBetween

**Comment by Aparna1Gopal** [comment]
**Notes**

- [Wiki](https://github.com/hackforla/UI-UX/wiki/past-speakers) updated 
- Issue is complete & being closed
