### ISSUE TITLE
User Experiences of Onboarding members at HfLA : February - March 2023

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/UI-UX#420]
### Overview
The goal of this project is to identify onboarding experiences for the newest members at Hack for LA. 

### Action Items
- [x] Formulate draft Research Plan
- [x] Review & revise with UI/UX CoP Co-leads
- [x] Send first draft of Research Plan using Reach Bonnie form
- [x] Recruit UX Researchers to work on this issue
- [x] Finalize [Research Plan](https://docs.google.com/document/d/12_ciIf_20UuqjuuqqCc4Xs2AyB17AKrqwH9jcWiMGs4/edit?usp=share_link), by UX Researchers
- [x] Finalize [Consent Form](https://docs.google.com/document/d/1qdrLsUvp0bofmmg7TdZvsZprX59n9sZ-LEv246mPQUk/edit?usp=share_link), by UX Researchers
- [x] Transfer Consent Form from Google Docs to [Google Form](https://docs.google.com/forms/d/1jkvK4FP6G1Mvj2n2J8C1u78--bpA15dksIkaAQfucE0/edit), by UX Researchers
- [x] Send GitHub Issue using Reach Bonnie form (by Feb 25)
- [x] Review & revise based on feedback from Bonnie
- [x] Assign teams & roles to UX Researchers
ON HOLD, As project has pivoted in a new direction
~~- [ ] Interview research participants (during Onboarding)~~
~~- [ ] Send Interview Recording(s) to team folder using this [Google Form]~~(https://docs.google.com/forms/d/1xEF9Cw-_4zOFK3_mBCF60HP7TEMIzdoa_FTlVT7qxrg/edit)~~
~~- [ ] Analyse data on Dovetail (affinity mapping workshops using qualitative data analysis tool)~~
~~- [ ] Create Slide Deck presentation/report of research findings~~
~~- [ ] Present & share Findings & Insights with Bonnie~~
~~- [ ] Present & share Findings & Insights with UI/UX Community of Practice~~ 
~~- [ ] Update Wiki~~

#### Resources for creating this issue
1.01 [Wiki Template: Mentor Research Output Overview](https://github.com/hackforla/internship/wiki/Mentor-Research-Overview)
1.02 [Wiki Template: Intern Research Output Overview](https://github.com/hackforla/internship/wiki/Intern-Research-Overview)
1.03 [Google Form Template: Internship Project Upload Recordings](https://docs.google.com/forms/d/e/1FAIpQLSfZ-SJAPQQECS_fH3AhDydAc06OpXu6JwjHfSuH6mpupiKb6A/viewform)

#### Resources gathered during the completion of this issue
2.01 [Google Drive Folder: HfLA Onboarding Experience](https://drive.google.com/drive/folders/1wy_Q3wL232gIiwkPU6My4DWFQxgwzGaX?usp=share_link)
2.02 [Google Doc: Research Plan](https://docs.google.com/document/d/12_ciIf_20UuqjuuqqCc4Xs2AyB17AKrqwH9jcWiMGs4/edit)
2.03 [Google Sheet: Hack for LA Onboarding Survey (Responses)](https://docs.google.com/spreadsheets/d/1tCRcDyEJvz8EXwqa2cfG-yXUz8ctrKuSx4dSzFHHTNc/edit?resourcekey#gid=145746317)
2.04 [Google Doc: Consent Document](https://docs.google.com/document/d/1qdrLsUvp0bofmmg7TdZvsZprX59n9sZ-LEv246mPQUk/edit)
2.05 [Google Form: Consent Form](https://docs.google.com/forms/d/1s-E8pBJ9RrHHLx5v557F9bC-OGf19Dp0VriuHIBPUjA/edit)
2.06 Google Doc: Interview Guide
2.07 Google Sheet: Interview Note-Taking
2.08 [Google Form: Upload Recordings](https://docs.google.com/forms/d/1xEF9Cw-_4zOFK3_mBCF60HP7TEMIzdoa_FTlVT7qxrg/edit)

**Comment by Aparna1Gopal** [comment]
**Notes** 
Sack messages with UXRs interested in this project 

Hi & Thank you for your interest again! We have drafted the [GitHub Issue](https://github.com/hackforla/UI-UX/issues/420) & are working to fine-tune it before we assign you. In the meantime, please review the TWE project. They have great best practices/templates in place for this kind of research. This Onboarding project you will be working on, is pretty bite-sized compared to TWE’s project. But the templates & processes will be of great help! So, feel free to look around & familiarize yourself with these docs.
I am also reaching out to the Leads of TWE & requesting them to add you to their drive. [Mentor Research Overview](https://github.com/hackforla/internship/wiki/Mentor-Research-Overview) & [Intern Research Overview](https://github.com/hackforla/internship/wiki/Intern-Research-Overview) are good places to start! Specifically look into the Research Plans & Consent Forms
As always, let us know if you have any further questions. Happy to help!

To TWE Leads 

Hi , I am one of the Co-Leads for the UI/UX Community of Practice. We are looking to conduct some UX Research during the next Onboarding. Could you please give 
[atJordan Turner]
[atL Leah Ellis]
[at Inbal Regev Lavy 
 permissions to access the Internship google drive? Such that they can get familiarized with the best practices/templates at TWE & replicate the same for their Onboarding project. Many thanks!

**Comment by Aparna1Gopal** [comment]
**Notes**
Slack message on the UI/UX Channel 
[at Jordan Turner]
[at Leah Ellis]
[at Inbal Regev Lavy]
[at Kevin]
[at Evan Stalker (he/him)]
 Hi! We are planning to conduct a meeting on Feb 23 (Thursday, 5-7PM PST). This will give us the opportunity to workshop all the documentation & materials required for your ‘UXR Onboarding Project’.
Please send us your email IDs & I will add you to the MS Teams Invite.

**Comment by Aparna1Gopal** [comment]
**Notes**
Qualitative DATA Analysis Resources 
To be used prior to data analysis workshops, prep work 
[How to Analyze Qualitative Data from UX Research: Thematic Analysis](https://www.nngroup.com/articles/thematic-analysis/)
[Qualitative Coding: How to Turn Complex Data into Conclusive Insights](https://www.userinterviews.com/blog/qualitative-coding-ux-research-analysis)

**Comment by Aparna1Gopal** [comment]
**Meeting/Workshop on Feb 23,2023**

**Agenda**

- [ ] Complete the UXR Roster
- [ ] Respond to all the immediate/burning questions by UXRs 
- [ ] Delegate following tasks to the UXRs:
 - [ ] Complete Research Plan 
 - [ ]  Consent forms - in Google Sheets 
 - [ ]  Consent forms - transfer to Google Form
- [ ] Discussion Guide to record User Interviews (Teams 1-5) with consent forms (Create templates & keep it ready) 
- [ ] One UXR as UXR Lead - to act as liaison between UI/UX CoP Co-Leads & all the UXRs working on this project - will be assigned to this issue 

-----------------------------------------------------

Next Week

Pair 2 UXRs – Interviewer & notetaker (on Feb 27)
Slide Deck for presentation (Aim for UXR findings to be presented on March 8,2023 during UI/UX CoP)

-----------------------------------------------------

Proposed Timeline

Feb 23 (Thur) – 2 hours: Meeting to workshop & delegate all required tasks 
Feb 24 (Friday) – 1 hour: Complete the Research Plans, Consent Forms, 
Feb 25 (Saturday) - Send Issue to Bonnie using Reach Bonnie Form 
Feb 27 (Monday): 2 hours : Workshop & training for UXRs to conduct user interviews 
Review & revise based on Bonnie’s feedback using ‘Reach Bonnie’ form 
Pilot test the Interview Guide 
Feb 28 (Tuesday): Conduct User Interviews during Onboarding 
March 2 & March 6: To workshop the Research findings 
March 8: Presentation of Research Findings & Insights, feedback from UI/UX CoP & Bonnie

**Comment by Aparna1Gopal** [comment]
**Meeting Notes**
**Meeting/Workshop on Feb 23,2023 - UI/UX Co-Leads & UXRs**

- Went over all the [Agenda items ](https://github.com/hackforla/UI-UX/issues/420#issuecomment-1441889265)

- Identified team's skillsets & interests 
- Team members on the project 
UI/UX CoP Co-leads providing ReOps & Research Management support 
Jennifer N 
Aparna G @

UXR Leads on the project
Kevin M 
Inbar L

UXRs Team 
Jordan T
Leah E
Inbal L
Evan S
Kevin M
gulsum

- Divided tasks amongst all team members 
Members working on Research Plan: Leah E, Evan S, Kevin M
Members working on Consent Forms: Jordan T, Inbal L, gulsum
Using templates & best practices from TWE/Internship project 
Note: Jordan T traveling this weekend so will be providing more documentation support during the latter half of this project (example: creating the slide decks etc.) 

- Meeting tomorrow, Feb 24 6PM-7PM PST to discuss documents/questions before sending GitHub Issue to Bonnie on Feb 25

- Meeting on Zoom, recording on Zoom to send to Kevin M who is in a different time zone 

- Jennifer N opened a new Slack channel for UXRs communication. Zoom link provided for meeting tomorrow. Aparna G sending out the Calendar invites. 

- Also spoke at length about the consent procedures & recording interviews/transcription options/using Otter AI/note takers etc. Identified & discussed all options, what UXRs are comfortable with, which will yield best data collection results, how to update the consent forms based on this etc. 
Aparna G reaching out to admin to see if UXRs can be given Co-host/panelist access on the Zoom call. The Zoom calls can be transcribed in real time, & the data can be analysed directly on a qualitative data analysis software. These transcription notes can be triangulated with the note-taker's notes. 
Aparna G also reaching out to admin to figure out how to lock/password protect this Google Drive & workspace for privacy of interviewees. 

- Aparna G to open a Dovetail account (qualitative data analysis software) using hfla email id, post data collection. The team can workshop the data analysis.

**Comment by Aparna1Gopal** [comment]
**Meeting Notes**
**Meeting/Workshop on Feb 24,2023 - UI/UX Co-Leads & UXRs**
6-7:30 PM PST

- Aparna G & Jennifer went over the housekeeping items. Communication with admin on Slack,Github/Drive permissions for team member, Walked through: Assigning this issue to the UXR Leads, Tagging [at] other team members on this GitHub issue (to be found in each member's GitHub profile under Issues-mentioned) 
- Inbar L as one of the UXR Leads went over the agenda. 
- Discussed the progress on the Research Plan. All members brainstormed on the ideas/questions & fine-tuned RP
- Discussed the progress on the Consent forms. All members brainstormed on the ideas/questions & fine-tuned content on the consent forms
- As requested by Bonnie, this GitHub issue with the Research Plan & Consent forms will be sent by Feb 25, at 5:30PM PST (as decided by team & accounting for the various/multiple timezones on this team) 
- Meeting was recorded to build this project's repository & also for the team members who were unable to make it. The meeting transcript & audio/video will be uploaded when the team is able to lock/password protect the project workspace & folder.

**Comment by Aparna1Gopal** [comment]
Meeting/Workshop on Feb 27,2023 - UI/UX Co-Leads & UXRs
ReOps & Research Management support provided by UI/UX CoP Co-Leads
UXR Leads conducting this meeting/workshop: Inbar L & Kevin M

Agenda
- [ ] Test out the following prior to user interviews:
  - [ ]  Interview Guide (pilot test)
  - [ ]   How will [Zoom recording in breakout rooms](https://support.zoom.us/hc/en-us/articles/201362473-Local-Recording)
- [ ] Review & revise based on Bonnie’s feedback using ‘Reach Bonnie’ form
- [ ] Other Items

**Comment by ExperimentsInHonesty** [comment]
@Aparna1Gopal @InbalRL I just lightly reviewed this document: [Research Plan](https://docs.google.com/document/d/12_ciIf_20UuqjuuqqCc4Xs2AyB17AKrqwH9jcWiMGs4/edit?usp=share_link).  It seems like it has a lot of unresolved strikeouts and comments.  I can review a final draft if you get it done today, otherwise I don't see this research happening next week.  I can't look at it past today because of other time commitments.  Please submit a new request via the reach Bonnie form

**Comment by ejstalker** [comment]
Thanks for reviewing, Bonnie. Sorry for any miscommunication, our target for having the document ready for you was actually 12pm PST today. We're on track to meet that deadline and would appreciate you taking a look after that if you can, thanks!

**Comment by Aparna1Gopal** [comment]
@ExperimentsInHonesty A new request via the Reach Bonnie form has been submitted. Thank you! 

@ejstalker Thanks for clarifying!

**Comment by Aparna1Gopal** [comment]
**Meeting/Workshop on Feb 27,2023 - UI/UX Co-Leads & UXRs**
ReOps & Research Management support provided by UI/UX CoP Co-Leads: Aparna G, Jennifer N, Julia G
UXR Leads: Inbar L & Kevin M

https://github.com/hackforla/UI-UX/issues/420#issuecomment-1445035404

**Comment by ExperimentsInHonesty** [comment]
[folder with recording 2023-02-28](https://drive.google.com/drive/folders/1hFf7k4iAY8agIETB7Qdi6MuSW9SnHAkR)

**Comment by kevinmoutoucarpin** [comment]
**Meeting/Workshop on March 3,2023 - UI/UX Co-Leads & UXRs**
ReOps & Research Management support provided by UI/UX CoP Co-Leads: Aparna G, Jennifer N, Julia G
UXR Leads conducting this meeting/workshop: Inbar L & Kevin M

Agenda

- [ ] Review Bonnie’s feedback
  - [ ] Formatting issues (Consent Form)
  - [ ] Branding issues (Research Plan, Consent Document & Consent Form)
  - [ ] File location issues (Documents with personal identifiable information need to be in a locked Drive such as Consent Form)
- [ ] Give feedback Research Plan (including Interview Guide)

**Comment by kevinmoutoucarpin** [comment]
**Meeting Notes**
**Meeting/Workshop on March 3,2023 - UI/UX Co-Leads & UXRs**
5:30-7:30 PM PST

- Gulsum created the consent form using HfLA branding.
- The team reviewed the Research Plan together (including the Interview Guide) and provided some feedback. They are now ready for Bonnie's review.
- Kevin will handle the file location issue (a part of it has been done by Aparna), which will be done in a few hours
- We need to choose a regular time for team meetings (will be decided later through Slack)

**Comment by kcoronel** [comment]
Hi @InbalRL thank you for using the Reach Bonnie form. It is unclear what documents you need Bonnie to review. Can you please write to Bonnie in a new comment and link the documents she needs to review. Please note that she will be in a car reading this on mobile. I pasted an example below: 

Here are the new documents that we need you to review: 
- List document 
- List document 

You can also briefly explain the changes within the comment. Let me know if you have any questions.

**Comment by Aparna1Gopal** [comment]
**Notes**

Managerial access has been provided to UI/UX CoP Co-Leads & UXR Leads, UXRs on this project.
[UI/UX - Interviews - (CoP)](https://drive.google.com/drive/folders/0AG8KFH3y9LwaUk9PVA)

**Comment by Aparna1Gopal** [comment]
**Notes:** 

This project is pivoting in a new direction from the initial requirements
 
The UXRs based on the requirements from Bonnie & admin (the stakeholders) will be completing the following: 
- Reach out to TWE to replicate best practices of creating GitHub Issues on Surveys & 1-1 Interviews 
- Create the ReOps structure for this project
- Analyze the Onboarding Survey Data (1 year of data from onboardings)
- Based on research findings from the survey data, the one on one interview questions/research will be conducted
- This above issue served as a test run for the Onboarding project – helped in getting the team upto with HfLA processes, & requirement for more collaboration with TWE Project for knowledge transfer. 
- Also spawned the requirements to create _training modules within the UI/UX CoP_. In order to replicate best practices from the TWE project & create efficient & accessible knowledge transfer 
- The issue is being closed.
-
