### ISSUE TITLE
Generate Questions for [2023-04-26]: Ciara(Kiki) Salmon

### ISSUE THREAD

**Issue by nguyen-jenn** [hackforla/UI-UX#428]
### Overview
We need to create a list of questions for our guest speaker Ciara(Kiki) Salmon attending on 2023-04-26.

### Action Items
- [x] Send issue to UI/UX Slack channel and ask UI/UX people to write their questions in the comments.
- [x] Collate the questions into a list of unique questions (non-duplicated questions).
- [x] Send them to the guest speakers within 2 weeks of their talk.

### Resources/Instructions
<details>
<summary>Slack Announcement (edit this)</summary>

:mega: Mark your Calendars! **Ciara(Kiki) Salmon** will be visiting the UI/UX Community of Practice on **2023-04-26**!

:computer: **Topic:** **Accessibility in UX**
  
? Please post **your questions** in this [GitHub issue](https://github.com/hackforla/UI-UX/issues/428) :arrow_left: :arrow_down: 
  
:bust_in_silhouette:**About:** Ciara (Kiki) Salmon is a user experience researcher at a contract agency who conducts research for companies such as Google.

:wave: [LinkedIn](https://www.linkedin.com/in/ciara-salmon/)

Thank you!
UI/UX CoP co-leads
@ Jennifer Nguyen @ Julia Gab @ Aparna Gopal

</details>

- [UI/UX Slack Channel](https://hackforla.slack.com/archives/C017ESHSMNG)
- https://www.linkedin.com/in/ciara-salmon

### Speaker Bio
Ciara (Kiki) Salmon is a user experience researcher at a contract agency who conducts research for companies such as Google. She has her undergraduate in cognitive psychology with emphasis in linguistics and her masters in occupational therapy. She practiced as a clinician prior to transitioning into the UX space and now specializes in accessibility. Previously Ciara has had volunteered for code for America through the HFLA and Code for San Jose brigades.  She primarily focuses on qualitative research but has began expanding into mixed method research.

**Comment by Aparna1Gopal** [comment]
**Questions:** 

- How can we as UX practitioners start looking to incorporate accessibility standards in our practice? Advice for UX Researchers, UX Designers, UX Writers. Would the advice/approach be similar or different?

- How can teams cross-collaborate across different domains (examples: UR’ers, PMs, Devs, other stakeholders) to make accessibility requirements a ‘must have’ rather than a ‘nice to have’?

**Comment by Aparna1Gopal** [comment]
**Slack communication with Admin:**

:mega: Mark your Calendars! Ciara(Kiki) Salmon will be visiting the UI/UX Community of Practice on 2023-04-26, 6PM PST!
:computer: Topic: Accessibility in UX
:bust_in_silhouette:About: Ciara (Kiki) Salmon is a user experience researcher at a contract agency who conducts research for companies such as Google.
:wave: [LinkedIn](https://www.linkedin.com/in/ciara-salmon/)
:question: Please post your questions in this [GitHub issue](https://github.com/hackforla/UI-UX/issues/428) :arrow_left:
Thank You!
:stopwatch: Register in advance for this webinar:
https://codeforamerica.zoom.us/webinar/register/WN_ytpQZroFT6CzR3onPz8Qkw
After registering, you will receive a confirmation email containing information about joining the webinar.

<img width="1020" alt="Screenshot 2023-04-05 at 1 20 55 pm" src="https://user-images.githubusercontent.com/86335455/230016426-289308aa-ec8c-4e5f-b287-90a397d073c2.png">

**Comment by Aparna1Gopal** [comment]
### Meet-Up link

[Accessibility in UX with Ciara (Kiki) Salmon](https://www.meetup.com/en-AU/hackforla/events/292714238/)

**Comment by nguyen-jenn** [comment]
Questions:

- Do you think accessible designs benefit every user?
- Do you have to take a course/earn a certification to be an "expert in accessibility"?
- What kinds of tests/research do you run to confirm a product is "accessible"?
- How do you if a product is "accessible" or "accessible enough"? In other words, what are the standards you try to adhere by?

**Comment by nguyen-jenn** [comment]
### Collated questions for Ciara (Kiki) Salmon

**Working with Accessibility in Career**

- How can we, as UX practitioners start looking to incorporate accessibility standards in our practice? Advice for UX Researchers, UX Designers, UX Writers. Would the advice/approach be similar or different?
- How can teams cross-collaborate across different domains (examples: UR’ers, PMs, Devs, other stakeholders) to make accessibility requirements a ‘must have’ rather than a ‘nice to have’?
- Do you have to take a course/earn a certification to be an "expert in accessibility"?

**What defines Accessibility**
- How would you differentiate between accessibility and inclusive design?
- What kinds of tests/research do you run to confirm a product is "accessible"?
- How do you know if a product is "accessible" or "accessible enough"? In other words, what are the standards you try to adhere by?

**Opinion on Accessibility**
- Do you think accessible designs benefit every user?

**Comment by nguyen-jenn** [comment]
**New Slack Announcement with Meetup Link**

:mega: Mark your Calendars! Ciara(Kiki) Salmon will be visiting the UI/UX Community of Practice on 2023-04-26!
:computer: Topic: Accessibility in UX
:bust_in_silhouette:About: Ciara (Kiki) Salmon is a user experience researcher at a contract agency who conducts research for companies such as Google.
:wave: [LinkedIn](https://www.linkedin.com/in/ciara-salmon/)
:question: Please post your questions in this [GitHub issue](https://github.com/hackforla/UI-UX/issues/428) :arrow_left:
:memo: Make sure to RSVP and register for the zoom webinar at this [link](https://www.meetup.com/hackforla/events/292714238/) :arrow_left:
Thank you!
UI/UX CoP co-leads
@Jennifer Nguyen @Julia Gab @Aparna Gopal

![Kiki_announcement](https://user-images.githubusercontent.com/69342220/232158348-a2c66b4a-1710-48c0-9779-544bd363943c.png)

**Comment by Aparna1Gopal** [comment]
### Resources shared during the Talk 

- Corien Staels: https://www.youtube.com/watch?v=NgXs34a1tJw
-  Corien Staels: https://wheelair.co.uk

**Comment by nguyen-jenn** [comment]
### Questions Collected During Event

Can you talk about the jump from academic research to your research at google. How did you make that leap and what insights might you offer about this process?

What do you think of getting 508 Certification training?

Besides the financial benefits accessibility brings that you mentioned, how do you advocate for accessible design to clients or stakeholders who are insistent on specific visual designs that aren’t accessible?

How do you make sure the product team incorprates accessibility early on?

What are technologies you're keeping an eye on at the forefront of accessibility development? eg ChatGPT4 for auto generated alt text

**Comment by Aparna1Gopal** [comment]
**Slack Message**

<img width="1002" alt="Screenshot 2023-04-27 at 7 44 47 am" src="https://user-images.githubusercontent.com/86335455/234753569-d7f9c01e-024e-42ef-943f-428344fdcb9b.png">

**Comment by Aparna1Gopal** [comment]
**Resources & Wiki Updated. Issue being closed.** 

:blob-wave:Thank You all for attending Kiki Salmon's talk on UX & Accessibility tonight!
:books:The resources shared during the talk can be found [here](https://github.com/hackforla/UI-UX/issues/428#issuecomment-1524406029)
:film_frames: The recording is available on our [Wiki](https://github.com/hackforla/UI-UX/wiki/Past-Speakers)!
