### ISSUE TITLE
Generate Questions for 2023-07-19: Jessa Anderson, PhD/ServiceNow

### ISSUE THREAD

**Issue by nguyen-jenn** [hackforla/UI-UX#470]
### Overview
We need to create a list of questions for our guest speaker Jessa Anderson, PhD attending on 2023-07-19.

### Action Items
- [x] Send issue to UI/UX Slack channel and ask UI/UX people to write their questions in the comments.
- [x] Collate the questions into a list of unique questions (non-duplicated questions).
- [x] Send them to the guest speakers within 2 weeks of their talk.

### Resources/Instructions
<details>
<summary>Slack Announcement (edit this)</summary>

:mega: Mark your Calendars! **Jessa Anderson, PhD** will be visiting the UI/UX Community of Practice on **2023-07-19**!

:computer: **Topic:** Developing Human Centered AI products through UX Research
  
? Please post **your questions** in this [GitHub issue](https://github.com/hackforla/UI-UX/issues/470) :arrow_left: :arrow_down: 
  
:bust_in_silhouette:**About:** With over a decade of research experience focused on human behavior, as an AI UX researcher and strategist at ServiceNow, Jessa Anderson focuses on helping the development and design of human-centered AI experiences. She works on collaborative cross-disciplinary teams to empower and elevate humans with responsible AI. With an emphasis on human-AI collaboration, she is currently helping to inform product development that balances the exciting potential of generative AI technology and capabilities, with user needs and expectations in collaborating with AI.

:wave: **[LinkedIn](https://www.linkedin.com/in/jessa-engelberg-anderson/)**

Thank you!
UI/UX CoP co-leads
@ Jennifer Nguyen @ Julia Gab @ Aparna Gopal

</details>

- [UI/UX Slack Channel](https://hackforla.slack.com/archives/C017ESHSMNG)
- [Linkedin](https://www.linkedin.com/in/jessa-engelberg-anderson/)

### Speaker Bio

With over a decade of research experience focused on human behavior, as an AI UX researcher and strategist at ServiceNow, Jessa Anderson focuses on helping the development and design of human-centered AI experiences. She works on collaborative cross-disciplinary teams to empower and elevate humans with responsible AI. With an emphasis on human-AI collaboration, she is currently helping to inform product development that balances the exciting potential of generative AI technology and capabilities, with user needs and expectations in collaborating with AI.

**Comment by Aparna1Gopal** [comment]
### Questions 

-  What recommendations/ideas do you have for UX Practitioners (Research, Design, Writing, Ops) in using AI in their day-to-day work? How can AI be used effectively in each of these domains to increase efficiency? 

- How can a UX Researcher upskill in AI to be job ready/marketable? Any recommendations for courses/certifications/bootcamps/degrees? 

- What are the different areas in AI that a UX Practitioner can specialise in? Which areas/specialities can have long-term returns in the job market? 

- What is the one question that we have not asked you yet regarding AI in UX, that we absolutely must know the answer to?

**Comment by Aparna1Gopal** [comment]
### Slack Announcement
- ON General & All-Leads channel ( to pass on message to other communities of practice) 
- Since Guest Speaker is an AI Specialist and may have good, applicable information for other communities of practice as well

:rotating_light: The UI/UX CoP is collecting questions for our next Guest Speaker, Jessa Anderson, PhD - An AI Specialist
[More Details](https://hackforla.slack.com/archives/C017ESHSMNG/p1688435268775199)
:alphabet-yellow-question:[Please post your questions here](https://github.com/hackforla/UI-UX/issues/470)
Thank You!

<img width="1058" alt="Screenshot 2023-07-09 at 2 55 54 pm" src="https://github.com/hackforla/UI-UX/assets/86335455/0cca989b-cf1b-4d29-b0ef-db2a15c12c87">

**Comment by nguyen-jenn** [comment]
### Slack Announcement

- ON UI/UX channel

![image](https://github.com/hackforla/UI-UX/assets/69342220/5e68cc46-88b8-4a88-8d37-f9a181838ebf)

**Comment by Aparna1Gopal** [comment]
### Slack Announcement

On UI/UX Slack Channel 

:rotating_light: The UI/UX CoP is collecting questions for our next Guest Speaker, Jessa Anderson, PhD - An AI Specialist
[More Details](https://hackforla.slack.com/archives/C017ESHSMNG/p1688435268775199)
:alphabet-yellow-question:[Please post your questions here](https://github.com/hackforla/UI-UX/issues/470)
Thank You!

<img width="1012" alt="Screenshot 2023-07-11 at 11 38 38 am" src="https://github.com/hackforla/UI-UX/assets/86335455/1a11953a-45e4-46c2-a193-26d7a3759ae2">

**Comment by nguyen-jenn** [comment]
### Questions

- What do you think is the main difference between working on developing a human centered design product that includes AI aspects versus one that does not?

- Do you think more and more products will now incorporate AI, and therefore we should all learn AI for better job prospects?

- How do you navigate around all the controversy/uncertainty with how some people feel toward AI especially trying to develop a product since products are to sell to consumers or serve people?

- For products utilizing AI, how can we maintain users' independence while ensuring the AI does it part in making processes more efficient? In other words, how do you find that balance of user and AI before it seems like AI is taking over our daily processes?

**Comment by juliagab56** [comment]
### Questions

- [Related to Aparna's first question] When it comes to AI tools I am only familiar with ChatGPT, can you talk about other AI software tools out there that you can recommend?

- Can you talk about working in cross disciplinary teams with AI? What does the understanding and communication of AI look like within multiple disciplines?

- What's a tip for making collaboration successful when it comes to a new technology like AI?

**Comment by nguyen-jenn** [comment]
### Collated Questions

**Getting more familiar with AI** 
- What recommendations/ideas do you have for UX Practitioners (Research, Design, Writing, Ops) in using AI in their day-to-day work? How can AI be used effectively in each of these domains to increase efficiency?
- When it comes to AI tools I am only familiar with ChatGPT, can you talk about other AI software tools out there that you can recommend?
- How can a UX Researcher upskill in AI to be job ready/marketable? Any recommendations for courses/certifications/bootcamps/degrees?

**Career with AI**
- What are the different areas in AI that a UX Practitioner can specialise in? Which areas/specialities can have long-term returns in the job market?
- Can you talk about working in cross disciplinary teams with AI? What does the understanding and communication of AI look like within multiple disciplines?
- What's a tip for making collaboration successful when it comes to a new technology like AI?
- What do you think is the main difference between working on developing a human centered design product that includes AI aspects versus one that does not?
- Do you think more and more products will now incorporate AI, and therefore we should all learn AI for better job prospects?

**Developing AI products with users in mind**
- How do you navigate around all the controversy/uncertainty with how some people feel toward AI especially trying to develop a product since products are to sell to consumers or serve people?
- For products utilizing AI, how can we maintain users' independence while ensuring the AI does it part in making processes more efficient? In other words, how do you find that balance of user and AI before it seems like AI is taking over our daily processes?

**Misc**
- What is the one question that we have not asked you yet regarding AI in UX, that we absolutely must know the answer to?

**Comment by Aparna1Gopal** [comment]
### Slack Announcement 

:bangbang:Please RSVP on this [meetup](https://www.meetup.com/hackforla/events/294652715/?utm_medium=referral&utm_campaign=share-btn_savedevents_share_modal&utm_source=link) and register for the [zoom link](https://us06web.zoom.us/webinar/register/WN_i4Q3s7IsQrO4BAlOIyeTrw#/registration) :bangbang:
:mega: Mark your Calendars! Jessa Anderson, PhD will be visiting the UI/UX Community of Practice on 2023-07-19!
:computer: Topic: Developing Human Centered AI products through UX Research
:bust_in_silhouette:About: With over a decade of research experience focused on human behavior, as an AI UX researcher and strategist at ServiceNow, Jessa Anderson focuses on helping the development and design of human-centered AI experiences. She works on collaborative cross-disciplinary teams to empower and elevate humans with responsible AI. With an emphasis on human-AI collaboration, she is currently helping to inform product development that balances the exciting potential of generative AI technology and capabilities, with user needs and expectations in collaborating with AI.
Thank you!
UI/UX CoP co-leads


<img width="1012" alt="Screenshot 2023-07-18 at 8 41 59 am" src="https://github.com/hackforla/UI-UX/assets/86335455/84a83e2c-b528-4a0a-bf55-2c741b176a67">

<img width="1029" alt="Screenshot 2023-07-18 at 8 42 10 am" src="https://github.com/hackforla/UI-UX/assets/86335455/1b219f2c-599b-44ef-911a-51ae36c76337">

**Comment by Aparna1Gopal** [comment]
### Questions during the Talk 

As a mom, I need to know what is in the dishes for my kids. How can users learn about transparency of algorithms that make AI?

Hi, how can you find hidden clusters within deep learning Ai. Or selfawareness Ai where, Ai seems to always find away?

How does the AI product incorporate privacy into design, research, or the overall team?

Will we be able to access the “Miro” in your slides?

My question is, (I might have missed the start of the slides) How is ServiceNow using this?  I only use ServiceNow with the ticket system.  (which i love!)

Regarding how Gen AI is currently very black-boxed in terms of how it works, have there been any efforts as far as you know to start making the Gen AI algorithms to be more explanatory and transparent?

You mentioned that you don't fully understand the technical aspects of AI. I'm curious, as a researcher or designer for the AI project, are there any differences compared to non-AI research or design? I've heard that it might require running different workshops or brainstorming sessions to support the engineering team in understanding how AI will work for the product?

With there be an diffrence of public,state, and federal cyber information allowed or not allowed to certain users.

There are plenty of resources available to teach researchers and designers how to use AI and ChatGPT to support their processes. How do ServiceNow response for this? do they allow researchers or designers to use ChatGPT or other AI tools for work?

**Comment by Aparna1Gopal** [comment]
### Resources shared by Speaker during the Talk 

<img width="826" alt="Screenshot 2023-07-20 at 7 03 40 am" src="https://github.com/hackforla/UI-UX/assets/86335455/14dd6cbc-3555-40a1-ade3-d92e44657ee9">

**Comment by Aparna1Gopal** [comment]
Resources & [Wiki](https://github.com/hackforla/UI-UX/wiki/past-speakers) Updated. Issue being closed.
