### ISSUE TITLE
Guest Speaker 2023: Create Consent Docs for Jessa A

### ISSUE THREAD

**Issue by nguyen-jenn** [hackforla/UI-UX#474]
### Overview
We need to create consent documents for guest speaker Jessa A so that we can keep track of what information is approved to be shared by the guest speaker. 

During these tasks you will be asked to add links to the Resources/Instructions section, and that section is at the bottom of this issue (go view it now).

#### Customize Resource Links
- Customize Resource for the 2023 Speaker Google Drive Folder
  - [x] Go to the main Google Drive Folder for the UI/UX Speakers (Resources # 1.01)
  - [x] Choose the folder for 2023. If one does not exist yet, follow the steps below. Strikethrough or delete the steps below if there is already a folder.
  - [x] Right-click on the 2023: Guest Speakers folder.
  - [x] Choose "Copy link".
  - [x] Update Resource # 2.01 with the link you just copied. Paste it inside parentheses at the end of the line.
  - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked.
- Customize Resource for This Speaker's Google Drive Folder
  - [x] Open the folder of Resource # 2.01.
  - [x] Copy the text below.
     ```
     Jessa A (July 19)
     ```
  - [x] Create a new folder (right click and select "New folder" or click the "+ New" button).
  - [x] Paste in the copied text and click "Create"
  - [x] Right-click on the folder that you just created.
  - [x] Choose "Get Link" and "Done"
  - [x] Update Resource # 2.02 with the link you just copied. Paste it inside parentheses at the end of the line.
  - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked.
- Customize Resource for this Speaker's Informed Consent Google Form
  - [x] Open the Informed Consent Form in Resources # 1.02.
  - [x] Choose the 3 vertical dots at the top of the Google Form on the left of your profile.
  - [x] Choose "Make a copy"
  - [x] Copy the text below
     ```
     2023: Jessa A: Presentation Recording Consent Form
     ```
  - [x] Paste the text you copied into the "Name" field to rename the form
  - [x] In the "Folder" field, choose "SpeakerConsentForm", then choose the back arrow to  "UI/UX Community of Practice"
  - [x] Choose "Speakers" > folder for 2023: Guest Speakers > folder for Jessa A
  - [x] Choose "Select"
  - [x] Choose "Make a copy"
  - [x] Update Resource # 2.03 link by completing the following steps
       - [x] Choose "Send" in the 2023: Jessa A: Presentation Recording Consent Form` you just created.
       - [x] Choose the link icon
       - [x] Check the box for "Shorten URL"
       - [x] Choose "Copy"
       - [x] Update Resource # 2.03 with the link you just copied. Place it into parentheses at the end of the line.
       - [x] Choose "Update comment" in GitHub and make sure all the checkboxes above have been checked.
- Customize Resource for this Speaker's Informed Consent Email
  - [x] Open the Speaker Consent Email Template in Resources # 1.03.
  - [x] Click "File" and select "Make a Copy"
  - [x] Copy the text below.
     ```
     2023: Jessa A: Speaker Consent Email
     ```
  - [x] Paste the text you copied into the "Name" field to rename the doc.
  - [x] In the "folder" field, choose "SpeakerConsentForm", then choose the back arrow to "UI/UX Community of Practice"
  - [x] Choose "Speakers" > folder for 2023: Guest Speakers > folder for Jessa A
  - [x] Choose "Select"
  - [x] Choose "Make a copy"
  - [x] Replace the highlighted text (including brackets) with the appropriate information
       - [x]  First name of guest speaker
       - [x]  Month and day of presentation
       - [x]  Link to Google Form (Resource # 2.03)
            - [x]  Copy the link for Resource # 2.03
            - [x]  Delete the text `[ADD LINK]`
            - [x]  Highlight to select the text `link`
            - [x]  Right-click and select "Insert link"
            - [x]  Paste link for Google Form
            - [x]  Click "Apply"
  - [x] Select all text
  - [x] Click the "Highlight color" icon
  - [x] Select "None"
  - [x] Click "File", select "Share", and select "Share with Others"
  - [x] Click "Copy link" and "Done"
  - [x] Update Resource # 2.04 with the link you just copied. Place it into parentheses at the end of the line.

#### Send Consent Documents
- [x] Assign CoP co-lead to issue
- [x] Unassign yourself (if not a CoP co-lead)
- [x] CoP co-lead reviews the Resources gathered during the completion of this issue.
- [x] CoP co-lead logs into uiux HfLA Gmail account
- [x] CoP co-lead copies and pastes email text from Resource # 2.04
- [x] CoP co-lead sends email to guest speaker at least one week before presentation

#### Resources for creating this issue
- 1.01 [Google Drive Folder: Speakers](https://drive.google.com/drive/folders/1QsvLA40-HbDc7VnKvIxHlowcef0R-EzY?usp=drive_link)
- 1.02 [Google Form: Consent for Presentation Recording](https://docs.google.com/forms/d/18CvB8eVk0fdHL7XeqID5nT5PIk1aSYDnQOkzLHEb-CY/edit)
- 1.03 [Google Doc: Speaker Consent Email Template](https://docs.google.com/document/d/12kHYsC32q-nywq1B0HaXmHomYN9CYtx5LOBIarAWYR0/edit?usp=drive_link)

#### Resources gathered during the completion of this issue
- 2.01 [[Google Drive Folder: 2023: Guest Speakers](https://drive.google.com/drive/folders/1VoRDgfiFNnVg3XEDF3euqoShpgzhDXi7?usp=drive_link)]
- 2.02 [[Google Drive Folder: Jessa A July 19](https://drive.google.com/drive/folders/1ht-RK4eBv8aGeKTi6DQkOLsiRkm_ALqT?usp=drive_link)]
- 2.03 [[Google Form: 2023: Jessa A: Presentation Recording Consent Form](https://forms.gle/UngTuEJC5TxVFtAN6)]
- 2.04 [[Google Doc: 2023: Jessa A Consent Email](https://docs.google.com/document/d/1HENuDAC7RJCq5hzKYbps4dk3SYatGm-igQlng4xmR7Y/edit?usp=sharing)]

**Comment by Aparna1Gopal** [comment]
Resources & [Wiki](https://github.com/hackforla/UI-UX/wiki/past-speakers) Updated. Issue being closed.
