### ISSUE TITLE
UX Experience Profile

### ISSUE THREAD

**Issue by bdavis73** [hackforla/UI-UX#49]
- [ ] Qualitiative interviews
- [ ] Surveys 
- [ ] Focus Groups
- [x] Completion of Guide for Community of practice. 
- [x] Completion of journey map for abc project - https://miro.com/app/board/o9J_lNsWcR0=/

**Comment by bdavis73** [comment]
Notation of completion of Guide for communities of practice.

**Comment by bdavis73** [comment]
Notation of completion of journey map with link.

**Comment by simrandhaliw** [comment]
Article title: Product Managers and UX Designers: Effective Communication Practices
Link of the wiki article: https://github.com/hackforla/UI-UX/wiki/Product-Managers-and-UX-Designers:-Effective-Communication-Practices

**Comment by simrandhaliw** [comment]
Journey Map title: UI/UX CoP Onboarding Prep
Link of the Journey Map: https://miro.com/app/board/o9J_lNsWcR0=/
