### ISSUE TITLE
Create a Universal Design System template for the entire organization

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/UI-UX#5]
### Overview
We will create a Universal Design System template for the entire organization that adheres to ADA guidelines

### Action Items
- [ ] Get set up on Figma
- [ ] Collate resources from projects
- [ ] Create a template 
- [ ] Create a user guide

### Resources/Instructions
[Hack for LA Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)
[Civic Tech Index Figma](https://www.figma.com/file/EFoSuj1b9G4aZ7bN8OX8tf/CivicTechIndex---Master-Design-File?node-id=1329%3A11944)
[100 Automations](https://www.figma.com/file/zGyhV8Z6sLohatYAnFoxQm/100Automations-Project-Board?node-id=243%3A363)

**Comment by meismith** [comment]
we started with small project design system first. We get some idea and inspiration from ballot nav and made some recommendation for typography and the colors. 
![Frame 75](https://user-images.githubusercontent.com/77039829/105789193-fc025b00-5f4f-11eb-8ba2-9a45c276a6c6.png)
![Text Color Hierarchy](https://user-images.githubusercontent.com/77039829/105789361-4daae580-5f50-11eb-8e58-58a988c07311.png)

Colors (in progress to add more)
![color](https://user-images.githubusercontent.com/77039829/105789406-62877900-5f50-11eb-82c5-8bc54383211c.png)


This is for the type scale
![typeScaleReccomendation](https://user-images.githubusercontent.com/77039829/105789232-0de3fe00-5f50-11eb-8a91-6f7ed6738971.png)
![Type Scale with Rubik](https://user-images.githubusercontent.com/77039829/105789246-12a8b200-5f50-11eb-91f8-2ab2068fa3b7.png)

There are some icons that we will consider to put into the design system for small project. Currently we are still working on it. But this is the progress so far
![Icons](https://user-images.githubusercontent.com/77039829/105789479-821ea180-5f50-11eb-9be6-06e38787ab31.png)

**Comment by daniellex0** [comment]
@meismith @ljhsu10 
Please provide update
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by fchan218** [comment]
<details><summary>Assignee, Labels, Project Board Placement, and Milestones for this issue in the UI/UX Repo:</summary>
<p>

<img width="387" alt="Screenshot 2024-10-23 at 8 05 58 PM" src="https://github.com/user-attachments/assets/167e5e87-cef6-43cd-a183-d254e96b64ac">
</p>
</details>

**Comment by fchan218** [comment]
@meismith @ljhsu10 @mklmrgn @salmonciara This guide issue is moving to the knowledgebase-content repo. If you would like to maintain edit access to the issue and its associated files, please fill out the [Google Drive Access Form](https://forms.gle/vnKRqprNYJUG5ET69).
