### ISSUE TITLE
Generate Questions for 2023-09-19: Sola Chang/Blizzard

### ISSUE THREAD

**Issue by nguyen-jenn** [hackforla/UI-UX#512]
### Overview
We need to create a list of questions for our guest speaker Sola Chang attending on 2023-09-19.

### Action Items
- [x] Send issue to UI/UX Slack channel and ask UI/UX people to write their questions in the comments.
- [x] Collate the questions into a list of unique questions (non-duplicated questions).
- [x] Send them to the guest speakers within 2 weeks of their talk.

### Resources/Instructions
<details>
<summary>Slack Announcement (edit this)</summary>

:mega: Mark your Calendars! **Sola Chang** will be visiting the UI/UX Community of Practice on **2023-09-19**!

:computer: **Topic:** Being a UI/UX Designer in Gaming
  
? Please post **your questions** in this [GitHub issue](https://github.com/hackforla/UI-UX/issues/512) :arrow_left: :arrow_down: 
  
:bust_in_silhouette:**About:** Well Met!  👋  I’m Sola, a UI/UX designer at Blizzard who works out of Seattle. I graduated with an English degree, then taught computer science in Korea, while juggling freelance art gigs in between (I have a very colorful background 😂). I’ve been on Hearthstone for almost two years now and have worked on some amazing projects for a range of players across the world and have been loving every moment of it!

:wave: **[LinkedIn](https://www.linkedin.com/in/sola8/)**

Thank you!
UI/UX CoP co-leads
@ Jennifer Nguyen @ Julia Gab @ Aparna Gopal

</details>

- [UI/UX Slack Channel](https://hackforla.slack.com/archives/C017ESHSMNG)
- [LinkedIn](https://www.linkedin.com/in/sola8/)

### Speaker Bio
Well Met!  👋  I’m Sola, a UI/UX designer at Blizzard who works out of Seattle. I graduated with an English degree, then taught computer science in Korea, while juggling freelance art gigs in between (I have a very colorful background 😂). I’ve been on Hearthstone for almost two years now and have worked on some amazing projects for a range of players across the world and have been loving every moment of it!

**Comment by Mssunnymuffins** [comment]
- Tell me about your career journey
- (If they did other UX) how did you get into UX for games?
- What's your day to day look like?
- What do you design? "Screens" like game menus, setup/"IA" like how the overall flow of the game will go for a player, or aspects of gameplay like how weapons should be swapped - or all? Or none?
- How closely do you work with everyone on the team? Are job titles strict or more fluid/intermingled?
- Do you do initial research? How so? What problem are you doing research on other than "users are bored? How can we solve this with a game?"? 
- What programs/tools do you use?
- What are the big differences you've noticed?
- Do you think someone needs a UX portfolio tailored to games? Or is making the transition with web and mobile case studies easy to do?
- Building off that - do you think it'd be easier to start in traditional UX and get a job in gaming UX once you have experience? Or do you have to stay in games?
- How's the job security and frequency in games?
- You don't how to tell me your specific numbers, but generally how does the salary compare to traditional UX? Is there equity?
- Is your work generally company based (do any projects for EA) or project based (work on this game and when the games done find a new job)?
- Which type of UX do you prefer?
- How passionate about games are you? Particularly games in the genre you're currently working on?
- Learning materials you'd recommend specifically for gaming UX and UI?
- Do you have any ideas for entry level projects? For example, traditional UX recommends hackathons or volunteering with civic tech orgs.

**Comment by Aparna1Gopal** [comment]
**Questions**
- We understand you are going to be Jennifer's peer/colleague at her Graduate school program. How do you see this Graduate program enhancing your skills as a UX Designer? Since you are already in the field & practicing? 
- What other recommendations would you have in terms of graduate programs, certificates, bootcamps for a Ux'er to upskill in Games UX Design?
- What tips & recommendations do you have for effectively & efficiently cross-collaborating with your team? What specialities/domains does your team comprise of? - - How does a game design org & team differ from an org/team in a different tech domain? Are there substantial differences & what recommendations do you have for someone looking to make this switch?

**Comment by nguyen-jenn** [comment]
**Career Journey**

- Tell me about your career journey
- (If they did other UX) how did you get into UX for games?

**Working as UX Designer in Gaming**

- What's your day to day look like?
- What do you design? "Screens" like game menus, setup/"IA" like how the overall flow of the game will go for a player, or aspects of gameplay like how weapons should be swapped - or all? Or none?
- Do you do initial research? How so? What problem are you doing research on other than "users are bored? How can we solve this with a game?"?
- What programs/tools do you use?
- How closely do you work with everyone on the team? What tips & recommendations do you have for effectively & efficiently cross-collaborating with your team? 
- Are job titles strict or more fluid/intermingled? What specialities/domains does your team comprise of? 
- How does a game design org & team differ from an org/team in a different tech domain? Are there substantial differences & what recommendations do you have for someone looking to make this switch?

**Tips to becoming a UX Designer in Gaming**

- Do you think someone needs a UX portfolio tailored to games? Or is making the transition with web and mobile case studies easy to do?
- Building off that - do you think it'd be easier to start in traditional UX and get a job in gaming UX once you have experience? Or do you have to stay in games?
- Do you have any ideas for entry level projects? For example, traditional UX recommends hackathons or volunteering with civic tech orgs.
- What other recommendations would you have in terms of graduate programs, certificates, bootcamps for a Ux'er to upskill in Games UX Design?
- Learning materials you'd recommend specifically for gaming UX and UI?

**Considering a Career in Gaming**

- How's the job security and frequency in games?
- You don't how to tell me your specific numbers, but generally how does the salary compare to traditional UX? Is there equity?
- Is your work generally company based (do any projects for Blizzard) or project based (work on this game and when the games done find a new job)? (If they've done both) Which type of UX do you prefer? Why?

**Misc**

- We understand you are going to be Jennifer's (our UI/UX Co-Lead's) peer/colleague at her Graduate school program. How do you see this Graduate program further enhancing your skills & profile as a UX Designer? Since you are already in the field & practicing?

**Comment by stephaniehua** [comment]
Sola's educational background and diverse career experiences is very inspiring. As a finance person who is trying to pivot into UX/UI design, I find it daunting to make such a drastic change. What inspired Sola to go from getting an English major, to teaching comp sci, to ultimately pivoting into UX/UI design? 

Is there any advice she could give in terms of pivoting into a completely new career? 

How did she hone her design skills and gain the proficiency to land a UX/UI design role without having prior experience?

What does she think about the current landscape of UX/UI and where it's headed, especially considering the introduction of AI?

**Comment by Aparna1Gopal** [comment]
### UI/UX Communities & Learning Resources shared by the Speaker

<img width="855" alt="Screenshot 2023-09-20 at 7 02 00 am" src="https://github.com/hackforla/UI-UX/assets/86335455/026047c3-0eb6-48a1-875e-c57b56ee50d1">

**Comment by Aparna1Gopal** [comment]
Guest Speaker 2023: Create Consent Docs for Sola C #513

**Comment by Aparna1Gopal** [comment]
Notes: 

- Updated [Wiki](https://github.com/hackforla/UI-UX/wiki/past-speakers)
- Issue complete & being closed
