### ISSUE TITLE
Workshop: Figma (The Basics)

### ISSUE THREAD

**Issue by juliagab56** [hackforla/UI-UX#525]
### Overview
- This is a workshop conducted during the weekly UI/UX Community of Practice meeting.
- The workshop's goal is to provide hands-on experience with various Figma basics, allowing volunteers to practice and gain proficiency

### Action Items
- [x] Intro convo (5 min)
    - “How proficient are you in Figma?”
    - "Does anyone have a specific interest in UI or graphic design?”
    - "What aspects of Figma do you want to improve?”
- [x] Identify and structure basic Figma concepts
    1. Overview of what Figma is and its significance to design (1-3 min)
       1. Figma is a cloud-based design platform that is broadly used amongst designers and it has tranformed the way they collaborate and create digital products. With Figma teams can design, prototype, and iterate on user interfaces in real-time. The platform has become an essential tool for most, as it fosters accessibility and seamless collaboration, enabling people of all backgrounds like designers, product managers, researchers, and developers to work together, from anywhere, to produce exceptional digital experiences.
    2. Figma anatomy (6 min)
        1. Left panel
            1. Layers
            2. Assets
            3. Pages
        2. Right panel
            1. Styles
            2. Properties/Tool bar
            3. Prototype
        3. Canvas
        4. Top bar
            1. Left actions
            2. Middle a
            3. Right a
    3. Plugins
    4. Create frame (1-3 min)
    5. Add shapes (6 min)
        1. Select, move, rotate, resize
        2. Change shape
        3. Change color
        4. Add stroke
        6. Add image 
    6. Add text (6min)
        1. Select, move, resize, 
        2. Kerning (space between letters) 
        3. Leading (space between lines)
        4. Change weight
        5. Change font
        7. Change color
    7. Shape + Text (button)
    8. Pen tool (6 min
    9. Group elements together (1-3 min)
    10. Comment (1-2 min)
    11. Export and Share (3 min)
- [x] Create templates and interactive workshop on [Figma](https://www.figma.com/file/SPhf15iJDyCajdOe7GP8N9/Workshops-(Public)?type=design&node-id=702%3A1476&mode=design&t=yMjx68481hl64YkE-1)
    - [x] One frame for each concept, contains: 
        - [x] Instructions for volunteers to learn about concept
        - [x] A section for volunteers to practice concept
- [x] Create instructions for workshop
    - Listen to the explanation of the Figma concept without disrupting, try not to move your cursor during explanations, please don't delete or change any templates on the canvas.
    - Take the time given to practice the concept in the playground area.
    - Ask questions by raising your hand, typing in the chat, or unmuting yourself.
    - If you have any tips, or better ways of doing something, we'd love it if you shared it with us. 
- [x] Collate all assets and put under Resources
- [x] Create [Slack announcement](https://hackforla.slack.com/archives/C017ESHSMNG/p1696986012591949) for Workshop
- [x] Share the Resources with the community, prior to the workshop, for quick prep/overview
- [x] Share link to the [Figma workspace](https://www.figma.com/file/SPhf15iJDyCajdOe7GP8N9/Workshops-(Public)?type=design&node-id=702%3A1476&mode=design&t=yMjx68481hl64YkE-1) and instructions, with the community during the workshop
- [x] Note any additional resources shared during the workshop, in this issue. Encourage community members to do the same.
- [x] Post WS Slack message wth extra resources and recording
- [x] Update resources in the Google Drive, if required
- [x] Update [Wiki](https://github.com/hackforla/UI-UX/wiki/Workshop-Series)
- [x] Share screenshot of collaborative Figma workspace in comments, if applicable
- [x] Review with Co-Leads & close issue

### Resources
[CoP Workshop Figma file](https://www.figma.com/file/SPhf15iJDyCajdOe7GP8N9/Workshops-(Public)?type=design&node-id=702%3A1476&mode=design&t=yMjx68481hl64YkE-1)
[Figma's Help center](https://help.figma.com/hc/en-us)
["Create Figma account" article](https://help.figma.com/hc/en-us/articles/360039811114)
[Figma official Youtube channel](https://www.youtube.com/@Figma)
[Figma for beginners Youtube playlist](https://youtube.com/playlist?list=PLXDU_eVOJTx7QHLShNqIXL1Cgbxj7HlN4&si=j-urCCHVlYrhN8zG)
[Figma tips Youtube playlist](https://youtube.com/playlist?list=PLXDU_eVOJTx6zk5MDarIs0asNoZqlRG23&si=662QmLSGkF3KP83q)
[Pen Tool Game](https://bezier.method.ac)
[Daily UI challenge](https://www.dailyui.co)

#### Slack messages
Pre meeting

> 📣 Hi everyone,
 This month is going to be all about Figma, and we can't wait to dive into it together! For our meetings in October we've lined up a few workshops, designed to help everyone, from beginners to seasoned pros, learn and get the most out of this awesome tool. We will start with the basics and build up from there.
  ℹ️ **Workshop Details:**  
     **What**: Figma: The basics
     **When**: Wednesday, Oct 11, at 6pm PST
    This workshop is going to be fun, interactive, and packed with useful tips. So mark your calendars and stay tuned for more info an resources coming your way. Let's make October a Figma-filled month to remember! 🎃🖌️💻
    See you there!
   ❗️ *A reminder that this meeting will be recorded for record keeping and as a public resource to current and new volunteers.*

Post meeting

> 📣 Hi community,
Thank you so much for joining us during our Figma workshop. We had a lot of information to go over and so little time! 
I encourage you to continue using the [Figma file](https://www.figma.com/file/SPhf15iJDyCajdOe7GP8N9/Workshops-(Public)?type=design&node-id=0%3A1&mode=design&t=aHLDg5IhSjhW89QA-1) we shared to:
1. Practice, in the playground section, the concepts we showed you, so you can start building your own UI elements and wireframes with ease.
2. Do the two activities at the far right "WIreframes" and "Logo Copywork". Follow the instructions and practice your Figma skills.
3. Check out all the resources. We already shared a few with you but there's additional ones like "Pen tool game" which is an awesome game to practice your pen tool dexterity, or the "Daily UI challenge" where you get to practice building UIs and win rewards. 
If you have any questions you want to ask or resources you want to share, let us know! 
**Workshop resources**
[Google Drive](https://drive.google.com/drive/folders/1j-Kgouo09Ugi347FH4pBJ-ml7RuEWZc0)
[Figma file](https://www.figma.com/file/SPhf15iJDyCajdOe7GP8N9/Workshops-(Public)?type=design&node-id=0%3A1&mode=design&t=aHLDg5IhSjhW89QA-1)
Next week we'll be hosting our **Figma: Intermediate** workshop, where we'll get to practice things like Autolayout and Components.

**Comment by juliagab56** [comment]
<img width="1227" alt="Screenshot 2023-10-12 at 9 24 18 AM" src="https://github.com/hackforla/UI-UX/assets/80308705/2316922a-f7ba-44ee-b9af-7c7be49131bd">

**Comment by Aparna1Gopal** [comment]
### Notes

Wiki also updated under the [Resources Section](https://github.com/hackforla/UI-UX/wiki/Workshop-Series)

**Comment by Aparna1Gopal** [comment]
### Slack Announcement 

:blob-wave:Hi community,
Thank you again for joining us this month at our Figma workshops. We had a lot of fun! :laptop_parrot:
I encourage you to continue using the Figma file we shared and check out all the workshops we did this month, [The basics](https://www.figma.com/file/SPhf15iJDyCajdOe7GP8N9/Workshops-(UI%2FUX-CoP%2C-Public)?type=design&node-id=701%3A2&mode=design&t=oxs7FzI3PxFy1Qpa-1) and [Intermediate pt1 & 2](https://www.figma.com/file/SPhf15iJDyCajdOe7GP8N9/Workshops-(UI%2FUX-CoP%2C-Public)?type=design&node-id=701%3A1195&mode=design&t=oxs7FzI3PxFy1Qpa-1):
1. Practice the concepts we showed you, so you can start building your own UI elements and wireframes with ease.
5. Do the final activities of each workshop to level up your Figma skills. Follow the instructions and practice.
6. Check out all the [Figma resources](https://www.figma.com/file/SPhf15iJDyCajdOe7GP8N9/Workshops-(UI%2FUX-CoP%2C-Public)?type=design&node-id=875%3A2571&mode=design&t=oxs7FzI3PxFy1Qpa-1) we shared and will continue sharing.
If you have any questions to ask or resources to share, let us know!
Recordings:
[Google Drive](https://drive.google.com/drive/folders/1j-Kgouo09Ugi347FH4pBJ-ml7RuEWZc0)


<img width="1049" alt="Screenshot 2023-11-01 at 2 49 48 pm" src="https://github.com/hackforla/UI-UX/assets/86335455/c887241f-fe86-4fe8-ae2a-b39a0f276741">
