### ISSUE TITLE
Workshop: Figma (Intermediate)

### ISSUE THREAD

**Issue by juliagab56** [hackforla/UI-UX#530]
### Overview
- This is a workshop conducted during the weekly UI/UX Community of Practice meeting.
- The workshop's goal is to provide hands-on experience with some Figma concepts, allowing volunteers to practice and gain proficiency

### Action Items
- [x] Identify and structure intermediate Figma concepts
    1. Autolayout
        - Constraits (only when a child element is within a parent)
        - Spacing
        - Direction
        - Padding
        - Resizing
            - Hug
            - Fill
            - Fixed
        - Absolute position
    2. Components
        - Variants
        - Instances
- [x] Create templates and interactive workshop on [Figma](https://www.figma.com/file/SPhf15iJDyCajdOe7GP8N9/Workshops-(Public)?type=design&node-id=1%3A2&mode=design&t=iqRp9Or6smEkRFBL-1)
    - [x] One frame for each concept, contains: 
        - [x] Instructions for volunteers to learn about concept
        - [x] A section for volunteers to practice concept
- [x] Create instructions for workshop
    - Listen to the explanation of the Figma concept without disrupting, try not to move your cursor during explanations, please don't delete or change any templates on the canvas.
    - Take the time given to practice the concept in the playground area.
    - Ask questions by raising your hand, typing in the chat, or unmuting yourself.
    - If you have any tips, or better ways of doing something, we'd love it if you shared it with us. 
- [x] Create Slack announcement for Workshop
- [x] Share link to the Figma workspace and instructions, with the community during the workshop
- [x] Note any additional resources shared during the workshop, in this issue. Encourage community members to do the same.
- [x] Post WS Slack message wth extra resources and recording
- [x] Update resources in the Google Drive, if required
- [x] Update [Wiki](https://github.com/hackforla/UI-UX/wiki/Workshop-Series)
- [x] Share screenshot of collaborative Figma workspace in comments, if applicable
- [x] Collate all assets and put under Resources
- [x] Share Resources with the community
- [x] Post WS survey
- [x] Review with Co-Leads & close issue

### Resources
[CoP Workshop Figma file](https://www.figma.com/file/SPhf15iJDyCajdOe7GP8N9/Workshops-(Public)?type=design&node-id=702%3A1476&mode=design&t=yMjx68481hl64YkE-1)
[Figma's Help center](https://help.figma.com/hc/en-us)
["Create Figma account" article](https://help.figma.com/hc/en-us/articles/360039811114)
[Figma official Youtube channel](https://www.youtube.com/@Figma)
[Figma for beginners Youtube playlist](https://youtube.com/playlist?list=PLXDU_eVOJTx7QHLShNqIXL1Cgbxj7HlN4&si=j-urCCHVlYrhN8zG)
[Figma tips Youtube playlist](https://youtube.com/playlist?list=PLXDU_eVOJTx6zk5MDarIs0asNoZqlRG23&si=662QmLSGkF3KP83q)
[Pen Tool Game](https://bezier.method.ac)
[Daily UI challenge](https://www.dailyui.co)
["Autolayout" Figma article](https://help.figma.com/hc/en-us/articles/360040451373-Explore-auto-layout-properties)
[Autolayout youtube video](https://www.youtube.com/watch?v=PGYCZbP3xH4&t=1832s)
["Components" Figma article](https://help.figma.com/hc/en-us/articles/360038662654-Guide-to-components-in-Figma)
[Components youtube video](https://www.youtube.com/watch?v=k74IrUNaJVk&list=PLXDU_eVOJTx5LSjOmeBYMuvaa4UayfMe4)

#### Slack messages
Pre meeting

> 📣Hi everyone,
We're excited to continue our Figma journey this month! Join us for the Figma Intermediate workshop, where we'll dive into the powerful features of Auto Layout and Components.
**Workshop Details:**
**What:** Figma Intermediate - Auto Layout and Components
**When:** Wednesday, Oct 18, at 6 pm PST
We'd like for this workshop to be an engaging and informative one so come participate. We're here to help you harness Figma's full potential. So, mark your calendars, and get ready for another knowledge-packed session.
Let's make October an unforgettable month of Figma mastery!
See you there!
*A reminder that this meeting will be recorded for record-keeping and as a public resource for current and new volunteers*

Post meeting

> 📣 Hi community,
Thank you again for joining us during another Figma workshop.
I encourage you to continue using the [Figma file](https://www.figma.com/file/SPhf15iJDyCajdOe7GP8N9/Workshops-(Public)?type=design&node-id=0%3A1&mode=design&t=aHLDg5IhSjhW89QA-1) we shared and check out both workshops, The basics and Intermediate:
1. Practice the concepts we showed you, so you can start building your own UI elements and wireframes with ease.
4. Do the final activities of each workshop to level up your Figma skills. Follow the instructions and practice.
5. Check out all the resources we shared and will continue sharing.
If you have any questions you want to ask or resources you want to share, let us know! 
**Workshop resources**
[Google Drive](https://drive.google.com/drive/folders/1j-Kgouo09Ugi347FH4pBJ-ml7RuEWZc0)
[Figma file](https://www.figma.com/file/SPhf15iJDyCajdOe7GP8N9/Workshops-(Public)?type=design&node-id=0%3A1&mode=design&t=aHLDg5IhSjhW89QA-1)
Next week we'll be hosting our ?.

**Comment by Aparna1Gopal** [comment]
### Notes

- Number of attendees - 15 (including 4 Co-leads)

**Comment by juliagab56** [comment]
<img width="1236" alt="Screenshot 2023-10-18 at 9 06 18 PM" src="https://github.com/hackforla/UI-UX/assets/80308705/c8f8a57d-c602-41c5-bb0b-b2f9d8144e25">

**Comment by juliagab56** [comment]
I will share resources with the community today and then complete this issue.
