### ISSUE TITLE
Generate Questions for 2024-01-10: Sara Gabriele/Coursera

### ISSUE THREAD

**Issue by pogwon** [hackforla/UI-UX#533]
### Overview
We need to create a list of questions for our guest speaker Sara Gabriele attending on 2024-01-10.

### Action Items
- [x] Send issue to UI/UX Slack channel and ask UI/UX people to write their questions in the comments.
- [ ] Collate the questions into a list of unique questions (non-duplicated questions).
- [ ] Send them to the guest speakers within 2 weeks of their talk.

### Resources/Instructions
<details>
<summary>Slack Announcement</summary>

:mega: Mark your Calendars! **Sara Gabriele** will be visiting the UI/UX Community of Practice on **2024-01-10**!

:computer: **Topic:** Breaking into UX: Early Career Discussion
  
Please post **your questions** in this [GitHub issue](https://github.com/hackforla/UI-UX/issues/533) :arrow_left: :arrow_down: 
  
:bust_in_silhouette:**About:** Sara is a UX Research Manager at Coursera, where she leads a team of researchers who work on advancing access to education worldwide through online learning. Sara began her career at Google, where she started as a Hiring Rotation Associate (HR program for new grads) and transitioned to become the first UX Researcher at Google Health. While at Google Health, her work included improving the usability of cancer diagnostic software, internationalizing an AI-powered eye disease diagnostic tool, and improving the user experience of finding health information on Google Search. Sara is passionate about helping aspiring researchers land their first UX role, and thrive once they’re in it. She lives in San Diego, CA with her husband Ziad and dog Ziggy.

:wave: [LinkedIn](https://www.linkedin.com/in/sara-gabriele-8849b3b2/)

Thank you!
UI/UX CoP co-leads
@ Jennifer Nguyen @ Julia Gab @ Aparna Gopal @ Peter Gwon

</details>

- [UI/UX Slack Channel](https://hackforla.slack.com/archives/C017ESHSMNG)
- [LinkedIn](https://www.linkedin.com/in/sara-gabriele-8849b3b2/)

### Speaker Bio
Sara is a UX Research Manager at Coursera, where she leads a team of researchers who work on advancing access to education worldwide through online learning. Sara began her career at Google, where she started as a Hiring Rotation Associate (HR program for new grads) and transitioned to become the first UX Researcher at Google Health. While at Google Health, her work included improving the usability of cancer diagnostic software, internationalizing an AI-powered eye disease diagnostic tool, and improving the user experience of finding health information on Google Search. Sara is passionate about helping aspiring researchers land their first UX role, and thrive once they’re in it. She lives in San Diego, CA with her husband Ziad and dog Ziggy.

**Comment by pogwon** [comment]
- How did you leverage your past experience when transitioning to your UX career? Do you have any advice for people who are switching careers?
- What was the process like for you as someone who transitioned into UX research from a different career path? How did you learn the necessary skills and gain experience to become a researcher?
- It seems that a lot of people are struggling to find jobs in UX, especially entry-level/junior roles. Do you feel the same way specifically about UX research roles, and where do you see this industry going in the next few years? What are good ways for people to stand out in such a competitive field?
- From your experience working with AI, how do you see it impacting UX careers for better or for worse?
- After graduating from a university/boot camp/course, what do you recommend for new designers and researchers to continue improving their skills?
- How often do you find yourself doing UX Design work as a researcher, if any? Are there any specific design skills you have had to learn?
- What made you want to switch from product design to specifically UX research?

**Comment by Aparna1Gopal** [comment]
- How has it been working for Google Health (health tech) versus Coursera (EdTech). What are the similarities and differences between the two domains/areas? Did you have to re-skill in some way to get upto speed as you switched from health tech to EdTech?

**Comment by juliagab56** [comment]
We reached out to speaker a few times but she's busy at the moment and will inform us when she can participate as a guest speaker. We are closing this in the meantime.
