### ISSUE TITLE
Create a Template for making composite images in our HfLA guides

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/UI-UX#55]
### Overview
We need to create a guide for making composite images in our HFLA guides so that all guides screenshots and header images can be consistent across all CoPs.

### Action Items
- [ ] Gather examples of how other Hack for LA projects or volunteers have done this (if applicable), adding each example as a link in the resources section below
   - [ ] Once done, remove the "Guide: Gather Examples" label and add the "Guide: Research" label
- [ ] Research existing information about [name of item] in [relevant resources, articles, etc.]
   - [ ] Once done, remove the "Guide: Research" label and add the "Guide: Draft Guide" label
- [ ] Create a draft guide, either in markdown format in this issue or a google doc in the [ux/ui google drive](https://drive.google.com/drive/u/1/folders/1os-4KyGnL0SXIeyfoDICOEpG5CO_1MaV)
    - [ ] Once done, remove the "Guide: Draft Guide" label and add the "Guide: Review Guide" label
- [ ] Review the guide with UX/UI community of practice
   - [ ] Once done, remove the "Guide: Review Guide" label and add the "Guide: Leadership Review" label
- [ ] Present to the Hack for LA leadership team for sign off
   - [ ] Once approved, remove the "Guide: Leadership Review" label and add the "Guide: Place Guide" label

### Resources
Update issue #15 with the name of item you are working on
### Resources/Instructions
[Make your screenshots and headers for your guide - TEMPLATE](https://docs.google.com/presentation/d/1xu_lYuucKkBKD9jWfLDZkEv3PkmIjcFEf0MnjEJdV5c/edit#slide=id.gcd1d3ada7a_0_31)

Original text: https://github.com/hackforla/UI-UX/issues/55#issuecomment-913588969

**Comment by ExperimentsInHonesty** [comment]
The header maybe should be the 
![Screen Shot 2021-04-15 at 2 31 10 PM](https://user-images.githubusercontent.com/37763229/114940854-3d8bff00-9df7-11eb-8e92-f8a983bf7593.png)

**Comment by Olivia-Chiong** [comment]
@daniellex0 We have a couple of guides on 100 Automations that could be helpful on this issue

[Screenshot example](https://github.com/100Automations/Website/blob/gh-pages/_guides/workflow-guide-for-ideators.md)
[Image highlighting example](https://github.com/100Automations/Website/blob/gh-pages/_guides/project_card_anatomy.md)

**Comment by ExperimentsInHonesty** [comment]
The guide bits 
![Screen Shot 2021-04-16 at 2 36 24 PM](https://user-images.githubusercontent.com/37763229/115086470-2a456600-9ec1-11eb-857a-163e4f0edafd.png)
should be part of the guide, not this template.  It was too confusing for the people we demoed it to today.

**Comment by daniellex0** [comment]
@ExperimentsInHonesty Sorry i didn't know you were going to demo this today, it actually wasn't ready yet! I need to remove the arrows because we agreed it should be just rectangles (and then potentially the annotation numbers/legend if or when necessary)- but that hadn't been finished yet. Sorry this is just a really crazy busy week for me.

**Comment by tan-zhou** [comment]
@Olivia-Chiong We'd like to see the examples from the 100-automation guide. Could you paste the link or screenshots here?

**Comment by daniellex0** [comment]
Another example to consider- Github's guides https://docs.github.com/en/organizations/keeping-your-organization-secure/requiring-two-factor-authentication-in-your-organization

**Comment by ExperimentsInHonesty** [comment]
@daniellex0 can you help me close out this issue?

**Comment by daniellex0** [comment]
Hi @ExperimentsInHonesty , this guide should be good to go 👍

**Comment by SheIsBukki** [comment]
### Overview
Community of Practice volunteers who are making Guides need a template to use for all screenshots and header images so that all guides can be consistent.

### Action Items
- [x] Make a slide deck
- [x] Create the following elements
   - [x] Arrows
   - [x] Anatomy
   - [x] Outlines 
   - [x] Headers - see issue: https://github.com/hackforla/product-management/issues/123#issuecomment-820695778
   
### Resources/Instructions
[Make your screenshots and headers for your guide - TEMPLATE](https://docs.google.com/presentation/d/1xu_lYuucKkBKD9jWfLDZkEv3PkmIjcFEf0MnjEJdV5c/edit#slide=id.gcd1d3ada7a_0_31)

**Comment by ExperimentsInHonesty** [comment]
This template is complete and we are now using it.  It is being linked to by this guide https://docs.google.com/document/d/1OyPfKqUU7ZinhjMoRmsXywyZfME_Oo_hpC2Zdxlb310/edit#

**Comment by ExperimentsInHonesty** [comment]
I added a link into the following WIKI page https://github.com/hackforla/UI-UX/wiki/UI-UX-Finished-Guides-and-Templates

**Comment by fchan218** [comment]
<details><summary>Assignee, Labels, Project Board Placement, and Milestones for this issue in the UI/UX Repo:</summary>
<p>
<img width="354" alt="Screenshot 2024-10-23 at 6 22 14 PM" src="https://github.com/user-attachments/assets/c2aea818-49fc-4e80-ba3a-b8fe191a0bb1">
</p>
</details>
