### ISSUE TITLE
Generate Questions for [2023-03-27]: [Brian Daniels/Pontoro | ex-R/GA, ex-ADP]

### ISSUE THREAD

**Issue by leopeng101** [hackforla/UI-UX#552]
### Overview
We need to create a list of questions for our guest speaker [PERSON - ROLE, COMPANY] attending on [DATE].

### Action Items
- [ ] Send issue to UI/UX Slack channel and ask UI/UX people to write their questions in the comments.
- [ ] Collate the questions into a list of unique questions (non-duplicated questions).
- [ ] Send them to the guest speakers within 2 weeks of their talk.

### Resources/Instructions
<details>
<summary>Slack Announcement (edit this)</summary>

:mega: Mark your Calendars! **[INSERT SPEAKER NAME][INSERT ROLE at COMPANY]** will be visiting the **UI/UX Community of Practice on [DATE] from [TIME]!**

:speech_balloon: **Topic:** [INSERT TITLE OF TALK]
 
:question: Please post your **questions** for [INSERT SPEAKER NAME] **here** [INSERT LINK TO GITHUB ISSUE] :arrow_backward:
 
:bust_in_silhouette: **About:** [INSERT SPEAKER BIO]

:star: [INSERT SPEAKER NAME]'s LinkedIn [INSERT LINK]

Thank you!
UI/UX CoP Co-Leads
[INSERT CURRENT COP CO-LEADS]

</details>

- [UI/UX Slack Channel](https://hackforla.slack.com/archives/C017ESHSMNG)
- WEBSITE/LINKEDIN: [INSERT NAME OF GUEST SPEAKER & LINK]

### Speaker Bio
Brian Daniels is a lead product designer at Pontoro creating a digital platform that's at the cross-section of traditional finance and tokenization. Before joining Pontoro, Brian led design at Lifion, by ADP and R/GA and has built and mentored high-performance design teams.

**Comment by Aparna1Gopal** [comment]
### Resources shared by Speaker

- Web 3 Job Search Platform: Braintrust

**Comment by Aparna1Gopal** [comment]
### Questions sent to Speaker

Started out in Product Management. What were the day to day tasks as a PM? 
What did you enjoy or not enjoy as much about being a PM? 
How did you get into UX? 
What initially got you interested in Crypto/Web3? 
What made you want to move or transition into the Web3 space from Crypto? 
What does designing for Crypto look like? 
How does the current AI craze impact Crypto/Web3? 
What is Pontoro trying to accomplish in this space?
How do you think Crypto can evolve with regulatory compliance? 
What are your thoughts on Crypto's environmental impact? 
How do you think we can popularize Crypto/Web3 as much as AI? 
How does Crypto/Web3 reduce cost for businesses? Is there a higher initial cost potentially? 
What are some DEI opportunities for Crypto/Web3?
