### ISSUE TITLE
UI/UX CoP: [Workshop Name - Date] 

### ISSUE THREAD

**Issue by juliagab56** [hackforla/UI-UX#567]
## Dependency
This issue needs to be made into a template and then it can be closed.

**Comment by Aparna1Gopal** [comment]
### Notes 
- The template was shared with the Co-Lead and feedback received. 
- [Template](https://github.com/hackforla/UI-UX/issues/new?assignees=&labels=&projects=&template=ui-ux_cop_workshops.md&title=UI%2FUX+CoP%3A+%5BYYYY-MM-DD%5D%3A+%5BWORKSHOP+NAME%5D) is finalised and the UI/UX Co-Leads will be using & iterating on this template as they conduct workshops for the CoP.
- Issue complete
