### ISSUE TITLE
Create a Guide & Template: Design Systems

### ISSUE THREAD

**Issue by daniellex0** [hackforla/UI-UX#61]
### Overview
We need to create a guide and a Figma template for Design Systems so that every project can know how to audit their designs and create their own design system / standardize their designs

### Action Items
- [ ] Gather examples of how other projects or volunteers have created their design systems, adding each example as a link in the resources section below
   - [ ] Once done, remove the "Guide: Gather Examples" label and add the "Guide: Research" label
- [ ] Research existing information about design systems in relevant resources, online articles, etc.
   - [ ] Once done, remove the "Guide: Research" label and add the "Guide: Draft Guide" label
- [ ] Create a draft guide, either in markdown format in this issue or a google doc in the [ux/ui google drive](https://drive.google.com/drive/u/1/folders/1os-4KyGnL0SXIeyfoDICOEpG5CO_1MaV)
    - [ ] Once done, remove the "Guide: Draft Guide" label and add the "Guide: Review Guide" label
- [ ] Review the guide with UX/UI community of practice
   - [ ] Once done, remove the "Guide: Review Guide" label and add the "Guide: Leadership Review" label
- [ ] Present to the Hack for LA leadership team for sign off
   - [ ] Once approved, remove the "Guide: Leadership Review" label and add the "Guide: Place Guide" label

### Resources
Update issue #15 with the name of item you are working on

**Comment by daniellex0** [comment]
This is now it's own project

**Comment by fchan218** [comment]
<details><summary>Assignee, Labels, Project Board Placement, and Milestones for this issue in the UI/UX Repo:</summary>
<p>

<img width="367" alt="Screenshot 2024-10-23 at 6 16 24 PM" src="https://github.com/user-attachments/assets/db830d85-d399-42e4-9601-d0a2efaf1fe3">
</p>
</details>

**Comment by fchan218** [comment]
@daniellex0 This guide issue is moving to the knowledgebase-content repo. If you would like to maintain edit access to the issue and its associated files, please fill out the [Google Drive Access Form](https://forms.gle/vnKRqprNYJUG5ET69).
