### ISSUE TITLE
Review new Recruiting Pipeline channel

### ISSUE THREAD

**Issue by Civic-Opportunity-Project** [hackforla/UI-UX#82]
[Pipeline sheet](https://docs.google.com/spreadsheets/d/1TuDelZ_pCg1pc9murZaYMsnv7CgEwXvoVtH5Jkt32XM/edit)

- [ ] Review HH Design (Facebook) in Row 19
- [ ] Set Display value (column L) to TRUE or FALSE

**Comment by rjdoria** [comment]
Zapier test completed. Pipeline doc now live.
