### ISSUE TITLE
Guide for developing a UX Research plan

### ISSUE THREAD

**Issue by Andre310** [hackforla/UI-UX#9]
### Overview
We need to create a UX Research plan topic guide to help UX Researchers learn to build and develop research questions.

### Action Items
- [ ] Gather existing information about research questions on HfLA
- [ ] Affinity mapping around resources
- [ ] Write a draft of guidance on using resources

### Resources/Instructions
[CFA Qual research guide](https://f.hubspotusercontent30.net/hubfs/5622333/CFA_QualitativeResearchGuide_v1.pdf)
[Existing HfLA project centered around research-BOP](https://github.com/codeforamerica/brigade-playbook/wiki/Process-overview)

[Developing a research plan](https://docs.google.com/document/d/1NP-ocqxpXJ__XZXDwkiTVIZlKy9yLOACnV2YaFcJBGU/edit?usp=sharing)

[GreenEarthOS Research Plan: Funder Analysis](https://docs.google.com/document/d/1tsHUusJK5bZWjeiSFOsfdwbC-u-rJxRtkKWbNB0E814/edit)

#### Contents
- Defining purpose/scope of the research
- Defining purpose/scope of individual questions
- Effective practices

**Comment by Andre310** [comment]
#### Updated recruitment email

Progress:  
- Went through the Qualitative research guide to find the focus on the research plan
- Started a google doc to organize the information I've found

To-do: 
- Organize research plan information from the CFA guide
- Organize research plan information from the BOP guide

Blockers:
- Na

**Comment by ExperimentsInHonesty** [comment]
This issue has been replaced by https://github.com/hackforla/UI-UX/issues/120

**Comment by fchan218** [comment]
<details><summary>Assignee, Labels, Project Board Placement, and Milestones for this issue in the UI/UX Repo:</summary>
<p>
<img width="365" alt="Screenshot 2024-10-23 at 8 04 33 PM" src="https://github.com/user-attachments/assets/b8761b28-0744-485c-ac4d-23e6d3d188ad">
</p>
</details>
