### ISSUE TITLE
Guide: How to Add Screenshots and Graphics to your Guide

### ISSUE THREAD

**Issue by daniellex0** [hackforla/UI-UX#92]
### Overview
We need to create a guide for how volunteers can annotate and add screenshots and graphics to their guides so that there can be consistency.

### Action Items
- [x] Research existing information about annotating guides in HfLA resources and online articles
   - [x] Once done, remove the "Guide: Research" label and add the "Guide: Gather Examples" label
- [x] Gather examples of how other projects or volunteers have done this (if any exist), adding each example as a link in the resources section below
   - [x] Once done, remove the "Guide: Gather Examples" label and add the "Guide: Draft Guide" label
- [x] Create a draft guide, either in markdown format in this issue or a google doc in the [ux/ui google drive]
    - [x] Once done, remove the "Guide: Draft Guide" label and add the "Guide: Review Guide" label
- [x] Review the guide with UX/UI community of practice
   - [x] Once done, remove the "Guide: Review Guide" label and add the "Guide: Leadership Review" label
- [x] Present to the Hack for LA leadership team for sign off
   - [x] Once approved, remove the "Guide: Leadership Review" label and add the "Guide: Place Guide" label

### Resources
Update issue #15 with the name of item you are working on

**Comment by anonymousanemone** [comment]
For devs adding this guide to the Toolkit page: the guide card Illustration and image credit information is in the [Toolkit page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967) (blue rectangle on bottom left)

**Comment by fchan218** [comment]
@daniellex0 This guide issue is moving to the knowledgebase-content repo. If you would like to maintain edit access to the issue and its associated files, please fill out the [Google Drive Access Form](https://forms.gle/vnKRqprNYJUG5ET69).
